// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix -target-feature +experimental-v -target-feature +f -target-feature +d -disable-O0-optnone -emit-llvm %s -o - | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @mconfig(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.msettype.i64(i64 [[A:%.*]]) #[[ATTR1:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.msettilem.i64(i64 [[A]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.msettilen.i64(i64 [[A]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.msettilek.i64(i64 [[A]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.msettypei.i64(i64 64) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = call i64 @llvm.riscv.msettilemi.i64(i64 32) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP6:%.*]] = call i64 @llvm.riscv.msettileni.i64(i64 64) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP7:%.*]] = call i64 @llvm.riscv.msettileki.i64(i64 128) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP8:%.*]] = call i64 @llvm.riscv.msettile.i64(i64 256) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP9:%.*]] = call i64 @llvm.riscv.msetoutsh.i64(i64 [[A]], i64 [[B:%.*]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP10:%.*]] = call i64 @llvm.riscv.msetinsh.i64(i64 [[A]], i64 [[B]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP11:%.*]] = call i64 @llvm.riscv.msetsk.i64(i64 [[A]], i64 [[B]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    [[TMP12:%.*]] = call i64 @llvm.riscv.msetpadval.i64(i64 [[A]]) #[[ATTR1]]
// CHECK-IR-RV64-NEXT:    ret void
//
void mconfig(size_t a, size_t b) {
    msettype(a);
    msettilem(a);
    msettilen(a);
    msettilek(a);
    msettypei(64);
    msettilemi(32);
    msettileni(64);
    msettileki(128);
    msettile(256);

    msetoutsh(a, b);
    msetinsh(a, b);
    msetsk(a, b);
    msetpadval(a);

    return;
}
