// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix \
// RUN: -target-feature +experimental-v -target-feature +f -target-feature +d \
// RUN: -target-feature +experimental-zfh -disable-O0-optnone -emit-llvm %s -o - \
// RUN: | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_fw_m_f16m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x float> @llvm.riscv.mlae.m.nxv64f32.i64(<vscale x 64 x float>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR5:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x half> @llvm.riscv.mfncvt.f.fw.m.nxv64f16.nxv64f32.i64(<vscale x 64 x float> [[TMP1]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f16.i64(<vscale x 64 x half> [[TMP2]], <vscale x 64 x half>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_fw_m_f16m1(const float *in1,  _Float16 *out, size_t a) {
    mfloat32m2_t m1 = mlae32_m2(in1, a);
    mfloat16m1_t mo = mfncvt_f_fw_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_fw_m_f32m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN1:%.*]] to <vscale x 32 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x double> @llvm.riscv.mlae.m.nxv32f64.i64(<vscale x 32 x double>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x float> @llvm.riscv.mfncvt.f.fw.m.nxv32f32.nxv32f64.i64(<vscale x 32 x double> [[TMP1]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f32.i64(<vscale x 32 x float> [[TMP2]], <vscale x 32 x float>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_fw_m_f32m1(const double *in1,  float *out, size_t a) {
    mfloat64m2_t m1 = mlae64_m2(in1, a);
    mfloat32m1_t mo = mfncvt_f_fw_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_f_m_f32m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN1:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlae.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x float> @llvm.riscv.mfwcvt.fw.f.m.nxv64f32.nxv64f16.i64(<vscale x 64 x half> [[TMP1]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f32.i64(<vscale x 64 x float> [[TMP2]], <vscale x 64 x float>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_f_m_f32m2(const _Float16 *in1,  float *out, size_t a) {
    mfloat16m1_t m1 = mlae16_m1(in1, a);
    mfloat32m2_t mo = mfwcvt_fw_f_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_f_m_f64m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlae.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x double> @llvm.riscv.mfwcvt.fw.f.m.nxv32f64.nxv32f32.i64(<vscale x 32 x float> [[TMP1]], i64 0) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 32 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f64.i64(<vscale x 32 x double> [[TMP2]], <vscale x 32 x double>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_f_m_f64m2(const float *in1,  double *out, size_t a) {
    mfloat32m1_t m1 = mlae32_m1(in1, a);
    mfloat64m2_t mo = mfwcvt_fw_f_m(m1);
    msae64_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_fw_m_f16m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 128 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x float> @llvm.riscv.mlae.m.nxv128f32.i64(<vscale x 128 x float>* [[TMP0]], i64 [[A:%.*]], i64 2) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 128 x half> @llvm.riscv.mfncvt.f.fw.m.nxv128f16.nxv128f32.i64(<vscale x 128 x float> [[TMP1]], i64 2) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 128 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv128f16.i64(<vscale x 128 x half> [[TMP2]], <vscale x 128 x half>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_fw_m_f16m2(const float *in1,  _Float16 *out, size_t a) {
    mfloat32m4_t m1 = mlae32_m4(in1, a);
    mfloat16m2_t mo = mfncvt_f_fw_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_f_m_f64m4(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x float> @llvm.riscv.mlae.m.nxv64f32.i64(<vscale x 64 x float>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x double> @llvm.riscv.mfwcvt.fw.f.m.nxv64f64.nxv64f32.i64(<vscale x 64 x float> [[TMP1]], i64 1) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 64 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f64.i64(<vscale x 64 x double> [[TMP2]], <vscale x 64 x double>* [[TMP3]], i64 [[A]], i64 2) #[[ATTR5]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_f_m_f64m4(const float *in1,  double *out, size_t a) {
    mfloat32m2_t m1 = mlae32_m2(in1, a);
    mfloat64m4_t mo = mfwcvt_fw_f_m(m1);
    msae64_m(mo, out, a);
    return;
}
