// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix \
// RUN: -target-feature +experimental-v -target-feature +f -target-feature +d \
// RUN: -target-feature +experimental-zfh -disable-O0-optnone -emit-llvm %s -o - \
// RUN: | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mfcvt_x_f_m_i16(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN1:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mfcvt.x.f.m.nxv64i16.nxv64f16(<vscale x 64 x half> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP2]], <vscale x 64 x i16>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mfcvt.h.hf.m.nxv64i16.nxv64f16(<vscale x 64 x half> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i16* [[OUT]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP4]], <vscale x 64 x i16>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_x_f_m_i16(const _Float16 *in1, int16_t *out, size_t a) {
    mfloat16_t m1 = mlc_m(in1, a);
    mint16_t mo = mfcvt_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvt_h_hf_m(m1);
    msc_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_x_f_m_i32(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mfcvt.x.f.m.nxv32i32.nxv32f32(<vscale x 32 x float> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP2]], <vscale x 32 x i32>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mfcvt.w.f.m.nxv32i32.nxv32f32(<vscale x 32 x float> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i32* [[OUT]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP4]], <vscale x 32 x i32>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_x_f_m_i32(const float *in1, int32_t *out, size_t a) {
    mfloat32_t m1 = mlc_m(in1, a);
    mint32_t mo = mfcvt_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvt_w_f_m(m1);
    msc_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_x_f_m_i64(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN1:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64.i64(<vscale x 16 x double>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mfcvt.x.f.m.nxv16i64.nxv16f64(<vscale x 16 x double> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP2]], <vscale x 16 x i64>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mfcvt.dw.d.m.nxv16i64.nxv16f64(<vscale x 16 x double> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i64* [[OUT]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP4]], <vscale x 16 x i64>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_x_f_m_i64(const double *in1, int64_t *out, size_t a) {
    mfloat64_t m1 = mlc_m(in1, a);
    mint64_t mo = mfcvt_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvt_dw_d_m(m1);
    msc_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvtu_x_f_m_i16(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN1:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mfcvtu.x.f.m.nxv64i16.nxv64f16(<vscale x 64 x half> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP2]], <vscale x 64 x i16>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mfcvtu.h.hf.m.nxv64i16.nxv64f16(<vscale x 64 x half> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i16* [[OUT]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP4]], <vscale x 64 x i16>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvtu_x_f_m_i16(const _Float16 *in1, uint16_t *out, size_t a) {
    mfloat16_t m1 = mlc_m(in1, a);
    muint16_t mo = mfcvtu_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvtu_h_hf_m(m1);
    msc_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvtu_x_f_m_i32(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mfcvtu.x.f.m.nxv32i32.nxv32f32(<vscale x 32 x float> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP2]], <vscale x 32 x i32>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mfcvtu.w.f.m.nxv32i32.nxv32f32(<vscale x 32 x float> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i32* [[OUT]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP4]], <vscale x 32 x i32>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvtu_x_f_m_i32(const float *in1, uint32_t *out, size_t a) {
    mfloat32_t m1 = mlc_m(in1, a);
    muint32_t mo = mfcvtu_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvtu_w_f_m(m1);
    msc_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvtu_x_f_m_i64(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN1:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64.i64(<vscale x 16 x double>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mfcvtu.x.f.m.nxv16i64.nxv16f64(<vscale x 16 x double> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP2]], <vscale x 16 x i64>* [[TMP3]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mfcvtu.dw.d.m.nxv16i64.nxv16f64(<vscale x 16 x double> [[TMP1]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast i64* [[OUT]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP4]], <vscale x 16 x i64>* [[TMP5]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvtu_x_f_m_i64(const double *in1, uint64_t *out, size_t a) {
    mfloat64_t m1 = mlc_m(in1, a);
    muint64_t mo = mfcvtu_x_f_m(m1);
    msc_m(mo, out, a);
    mo = mfcvtu_dw_d_m(m1);
    msc_m(mo, out, a);
    return;
}
