// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix \
// RUN: -target-feature +experimental-v -target-feature +f -target-feature +d \
// RUN: -target-feature +experimental-zfh -disable-O0-optnone -emit-llvm %s -o - \
// RUN: | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mfcvt_f_x_m_f16m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlae.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x half> @llvm.riscv.mfcvt.f.x.m.nxv64f16.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f16.i64(<vscale x 64 x half> [[TMP2]], <vscale x 64 x half>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_f_x_m_f16m1(const int16_t *in1,  _Float16 *out, size_t a) {
    mint16m1_t m1 = mlae16_m1(in1, a);
    mfloat16m1_t mo = mfcvt_f_x_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_f_x_m_f32m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN1:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlae.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x float> @llvm.riscv.mfcvt.f.x.m.nxv32f32.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f32.i64(<vscale x 32 x float> [[TMP2]], <vscale x 32 x float>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_f_x_m_f32m1(const int32_t *in1,  float *out, size_t a) {
    mint32m1_t m1 = mlae32_m1(in1, a);
    mfloat32m1_t mo = mfcvt_f_x_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_f_x_m_f64m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN1:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlae.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x double> @llvm.riscv.mfcvt.f.x.m.nxv16f64.nxv16i64.i64(<vscale x 16 x i64> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv16f64.i64(<vscale x 16 x double> [[TMP2]], <vscale x 16 x double>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_f_x_m_f64m1(const int64_t *in1,  double *out, size_t a) {
    mint64m1_t m1 = mlae64_m1(in1, a);
    mfloat64m1_t mo = mfcvt_f_x_m(m1);
    msae64_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_xw_m_f16m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN1:%.*]] to <vscale x 64 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i32> @llvm.riscv.mlae.m.nxv64i32.i64(<vscale x 64 x i32>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x half> @llvm.riscv.mfncvt.f.xw.m.nxv64f16.nxv64i32.i64(<vscale x 64 x i32> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f16.i64(<vscale x 64 x half> [[TMP2]], <vscale x 64 x half>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_xw_m_f16m1(const int32_t *in1,  _Float16 *out, size_t a) {
    mint32m2_t m1 = mlae32_m2(in1, a);
    mfloat16m1_t mo = mfncvt_f_xw_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_xw_m_f32m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN1:%.*]] to <vscale x 32 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i64> @llvm.riscv.mlae.m.nxv32i64.i64(<vscale x 32 x i64>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x float> @llvm.riscv.mfncvt.f.xw.m.nxv32f32.nxv32i64.i64(<vscale x 32 x i64> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f32.i64(<vscale x 32 x float> [[TMP2]], <vscale x 32 x float>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_xw_m_f32m1(const int64_t *in1,  float *out, size_t a) {
    mint64m2_t m1 = mlae64_m2(in1, a);
    mfloat32m1_t mo = mfncvt_f_xw_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_f_xq_m_f16m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN1:%.*]] to <vscale x 64 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i64> @llvm.riscv.mlae.m.nxv64i64.i64(<vscale x 64 x i64>* [[TMP0]], i64 [[A:%.*]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x half> @llvm.riscv.mfncvt.f.xq.m.nxv64f16.nxv64i64.i64(<vscale x 64 x i64> [[TMP1]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f16.i64(<vscale x 64 x half> [[TMP2]], <vscale x 64 x half>* [[TMP3]], i64 [[A]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_f_xq_m_f16m1(const int64_t *in1,  _Float16 *out, size_t a) {
    mint64m4_t m1 = mlae64_m4(in1, a);
    mfloat16m1_t mo = mfncvt_f_xq_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_x_m_f16m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlae.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 128 x half> @llvm.riscv.mfwcvt.fw.x.m.nxv128f16.nxv128i8.i64(<vscale x 128 x i8> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 128 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv128f16.i64(<vscale x 128 x half> [[TMP2]], <vscale x 128 x half>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_x_m_f16m2(const int8_t *in1,  _Float16 *out, size_t a) {
    mint8m1_t m1 = mlae8_m1(in1, a);
    mfloat16m2_t mo = mfwcvt_fw_x_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_x_m_f32m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlae.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x float> @llvm.riscv.mfwcvt.fw.x.m.nxv64f32.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f32.i64(<vscale x 64 x float> [[TMP2]], <vscale x 64 x float>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_x_m_f32m2(const int16_t *in1,  float *out, size_t a) {
    mint16m1_t m1 = mlae16_m1(in1, a);
    mfloat32m2_t mo = mfwcvt_fw_x_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwcvt_fw_x_m_f64m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN1:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlae.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x double> @llvm.riscv.mfwcvt.fw.x.m.nxv32f64.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], i64 0) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 32 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f64.i64(<vscale x 32 x double> [[TMP2]], <vscale x 32 x double>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwcvt_fw_x_m_f64m2(const int32_t *in1,  double *out, size_t a) {
    mint32m1_t m1 = mlae32_m1(in1, a);
    mfloat64m2_t mo = mfwcvt_fw_x_m(m1);
    msae64_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_fw_xw_m_f16m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 128 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i16> @llvm.riscv.mlae.m.nxv128i16.i64(<vscale x 128 x i16>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 128 x half> @llvm.riscv.mfcvt.fw.xw.m.nxv128f16.nxv128i16.i64(<vscale x 128 x i16> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 128 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv128f16.i64(<vscale x 128 x half> [[TMP2]], <vscale x 128 x half>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_fw_xw_m_f16m2(const int16_t *in1,  _Float16 *out, size_t a) {
    mint16m2_t m1 = mlae16_m2(in1, a);
    mfloat16m2_t mo = mfcvt_fw_xw_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_fw_xw_m_f32m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN1:%.*]] to <vscale x 64 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i32> @llvm.riscv.mlae.m.nxv64i32.i64(<vscale x 64 x i32>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x float> @llvm.riscv.mfcvt.fw.xw.m.nxv64f32.nxv64i32.i64(<vscale x 64 x i32> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f32.i64(<vscale x 64 x float> [[TMP2]], <vscale x 64 x float>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_fw_xw_m_f32m2(const int32_t *in1,  float *out, size_t a) {
    mint32m2_t m1 = mlae32_m2(in1, a);
    mfloat32m2_t mo = mfcvt_fw_xw_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_fw_xw_m_f64m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN1:%.*]] to <vscale x 32 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i64> @llvm.riscv.mlae.m.nxv32i64.i64(<vscale x 32 x i64>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x double> @llvm.riscv.mfcvt.fw.xw.m.nxv32f64.nxv32i64.i64(<vscale x 32 x i64> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 32 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f64.i64(<vscale x 32 x double> [[TMP2]], <vscale x 32 x double>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_fw_xw_m_f64m2(const int64_t *in1,  double *out, size_t a) {
    mint64m2_t m1 = mlae64_m2(in1, a);
    mfloat64m2_t mo = mfcvt_fw_xw_m(m1);
    msae64_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfncvt_fw_xq_m_f32m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN1:%.*]] to <vscale x 64 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i64> @llvm.riscv.mlae.m.nxv64i64.i64(<vscale x 64 x i64>* [[TMP0]], i64 [[A:%.*]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x float> @llvm.riscv.mfncvt.fw.xq.m.nxv64f32.nxv64i64.i64(<vscale x 64 x i64> [[TMP1]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f32.i64(<vscale x 64 x float> [[TMP2]], <vscale x 64 x float>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfncvt_fw_xq_m_f32m2(const int64_t *in1,  float *out, size_t a) {
    mint64m4_t m1 = mlae64_m4(in1, a);
    mfloat32m2_t mo = mfncvt_fw_xq_m(m1);
    msae32_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_f_x_m_f16m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 128 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i16> @llvm.riscv.mlae.m.nxv128i16.i64(<vscale x 128 x i16>* [[TMP0]], i64 [[A:%.*]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 128 x half> @llvm.riscv.mfcvt.f.x.m.nxv128f16.nxv128i16.i64(<vscale x 128 x i16> [[TMP1]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 128 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv128f16.i64(<vscale x 128 x half> [[TMP2]], <vscale x 128 x half>* [[TMP3]], i64 [[A]], i64 1) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_f_x_m_f16m2(const int16_t *in1,  _Float16 *out, size_t a) {
    mint16m2_t m1 = mlae16_m2(in1, a);
    mfloat16m2_t mo = mfcvt_f_x_m(m1);
    msae16_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfcvt_f_x_m_f16m4(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 256 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 256 x i16> @llvm.riscv.mlae.m.nxv256i16.i64(<vscale x 256 x i16>* [[TMP0]], i64 [[A:%.*]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = call <vscale x 256 x half> @llvm.riscv.mfcvt.f.x.m.nxv256f16.nxv256i16.i64(<vscale x 256 x i16> [[TMP1]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 256 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv256f16.i64(<vscale x 256 x half> [[TMP2]], <vscale x 256 x half>* [[TMP3]], i64 [[A]], i64 2) #[[ATTR6]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfcvt_f_x_m_f16m4(const int16_t *in1,  _Float16 *out, size_t a) {
    mint16m4_t m1 = mlae16_m4(in1, a);
    mfloat16m4_t mo = mfcvt_f_x_m(m1);
    msae16_m(mo, out, a);
    return;
}
