// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix -target-feature +experimental-v -target-feature +f -target-feature +d -disable-O0-optnone -emit-llvm %s -o - | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s

#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_v_mlce8_msce8_vint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 8 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 8 x i8> @llvm.riscv.mlce.v.nxv8i8.i64(<vscale x 8 x i8>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 8 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv8i8.i64(<vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce8_msce8_vint8_m1(const int8_t *in1, int8_t *out, size_t a) {
    vint8m1_t m1 = mlce8_v(in1, a);
    msce8_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce8_msce8_vuint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN:%.*]] to <vscale x 8 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 8 x i8> @llvm.riscv.mlce.v.nxv8i8.i64(<vscale x 8 x i8>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 8 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv8i8.i64(<vscale x 8 x i8> [[TMP1]], <vscale x 8 x i8>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce8_msce8_vuint8_m1(const uint8_t *in, uint8_t *out, size_t a) {
    vuint8m1_t m1 = mlce8_v(in, a);
    msce8_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce16_msce16_vint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 4 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i16> @llvm.riscv.mlce.v.nxv4i16.i64(<vscale x 4 x i16>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 4 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv4i16.i64(<vscale x 4 x i16> [[TMP1]], <vscale x 4 x i16>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce16_msce16_vint16_m1(const int16_t *in, int16_t *out, size_t a) {
    vint16m1_t m1 = mlce16_v(in, a);
    msce16_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce16_msce16_vuint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 4 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i16> @llvm.riscv.mlce.v.nxv4i16.i64(<vscale x 4 x i16>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 4 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv4i16.i64(<vscale x 4 x i16> [[TMP1]], <vscale x 4 x i16>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce16_msce16_vuint16_m1(const uint16_t *in, uint16_t *out, size_t a) {
    vuint16m1_t m1 = mlce16_v(in, a);
    msce16_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce16_msce16_vfloat16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN:%.*]] to <vscale x 4 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x half> @llvm.riscv.mlce.v.nxv4f16.i64(<vscale x 4 x half>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 4 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv4f16.i64(<vscale x 4 x half> [[TMP1]], <vscale x 4 x half>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce16_msce16_vfloat16_m1(const _Float16 *in, _Float16 *out, size_t a) {
    vfloat16m1_t m1 = mlce16_v(in, a);
    msce16_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce32_msce32_vint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 2 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.riscv.mlce.v.nxv2i32.i64(<vscale x 2 x i32>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 2 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv2i32.i64(<vscale x 2 x i32> [[TMP1]], <vscale x 2 x i32>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce32_msce32_vint32_m1(const int32_t *in, int32_t *out, size_t a) {
    vint32m1_t m1 = mlce32_v(in, a);
    msce32_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce32_msce32_vuint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 2 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.riscv.mlce.v.nxv2i32.i64(<vscale x 2 x i32>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 2 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv2i32.i64(<vscale x 2 x i32> [[TMP1]], <vscale x 2 x i32>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce32_msce32_vuint32_m1(const uint32_t *in, uint32_t *out, size_t a) {
    vuint32m1_t m1 = mlce32_v(in, a);
    msce32_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce32_msce32_vfloat32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN:%.*]] to <vscale x 2 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x float> @llvm.riscv.mlce.v.nxv2f32.i64(<vscale x 2 x float>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 2 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv2f32.i64(<vscale x 2 x float> [[TMP1]], <vscale x 2 x float>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce32_msce32_vfloat32_m1(const float *in, float *out, size_t a) {
    vfloat32m1_t m1 = mlce32_v(in, a);
    msce32_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce64_msce64_vint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 1 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x i64> @llvm.riscv.mlce.v.nxv1i64.i64(<vscale x 1 x i64>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 1 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv1i64.i64(<vscale x 1 x i64> [[TMP1]], <vscale x 1 x i64>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce64_msce64_vint64_m1(const int64_t *in, int64_t *out, size_t a) {
    vint64m1_t m1 = mlce64_v(in, a);
    msce64_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce64_msce64_vuint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 1 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x i64> @llvm.riscv.mlce.v.nxv1i64.i64(<vscale x 1 x i64>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 1 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv1i64.i64(<vscale x 1 x i64> [[TMP1]], <vscale x 1 x i64>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce64_msce64_vuint64_m1(const uint64_t *in, uint64_t *out, size_t a) {
    vuint64m1_t m1 = mlce64_v(in, a);
    msce64_v(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_v_mlce64_msce64_vfloat64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN:%.*]] to <vscale x 1 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x double> @llvm.riscv.mlce.v.nxv1f64.i64(<vscale x 1 x double>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 1 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msce.v.nxv1f64.i64(<vscale x 1 x double> [[TMP1]], <vscale x 1 x double>* [[TMP2]], i64 [[A]]) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_v_mlce64_msce64_vfloat64_m1(const double *in, double *out, size_t a) {
    vfloat64m1_t m1 = mlce64_v(in, a);
    msce64_v(m1, out, a);

    return;
}
