// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix -target-feature +experimental-v -target-feature +f -target-feature +d -disable-O0-optnone -emit-llvm %s -o - | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mlbe8_msbe8_mint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlbe.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv128i8.i64(<vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe8_msbe8_mint8_m1(const int8_t *in1, int8_t *out, size_t a) {
    mint8m1_t m1 = mlbe8_m1(in1, a);
    msbe8_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe8_msbe8_muint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlbe.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv128i8.i64(<vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe8_msbe8_muint8_m1(const uint8_t *in, uint8_t *out, size_t a) {
    muint8m1_t m1 = mlbe8_m1(in, a);
    msbe8_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe16_msbe16_mint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlbe.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe16_msbe16_mint16_m1(const int16_t *in, int16_t *out, size_t a) {
    mint16m1_t m1 = mlbe16_m1(in, a);
    msbe16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe16_msbe16_muint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlbe.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe16_msbe16_muint16_m1(const uint16_t *in, uint16_t *out, size_t a) {
    muint16m1_t m1 = mlbe16_m1(in, a);
    msbe16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe16_msbe16_mfloat16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlbe.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv64f16.i64(<vscale x 64 x half> [[TMP1]], <vscale x 64 x half>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe16_msbe16_mfloat16_m1(const _Float16 *in, _Float16 *out, size_t a) {
    mfloat16m1_t m1 = mlbe16_m1(in, a);
    msbe16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe32_msbe32_mint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlbe.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe32_msbe32_mint32_m1(const int32_t *in, int32_t *out, size_t a) {
    mint32m1_t m1 = mlbe32_m1(in, a);
    msbe32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe32_msbe32_muint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlbe.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe32_msbe32_muint32_m1(const uint32_t *in, uint32_t *out, size_t a) {
    muint32m1_t m1 = mlbe32_m1(in, a);
    msbe32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe32_msbe32_mfloat32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlbe.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv32f32.i64(<vscale x 32 x float> [[TMP1]], <vscale x 32 x float>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe32_msbe32_mfloat32_m1(const float *in, float *out, size_t a) {
    mfloat32m1_t m1 = mlbe32_m1(in, a);
    msbe32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe64_msbe64_mint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlbe.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP1]], <vscale x 16 x i64>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe64_msbe64_mint64_m1(const int64_t *in, int64_t *out, size_t a) {
    mint64m1_t m1 = mlbe64_m1(in, a);
    msbe64_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe64_msbe64_muint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlbe.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP1]], <vscale x 16 x i64>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe64_msbe64_muint64_m1(const uint64_t *in, uint64_t *out, size_t a) {
    muint64m1_t m1 = mlbe64_m1(in, a);
    msbe64_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbe64_msbe64_mfloat64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x double> @llvm.riscv.mlbe.m.nxv16f64.i64(<vscale x 16 x double>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbe.m.nxv16f64.i64(<vscale x 16 x double> [[TMP1]], <vscale x 16 x double>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbe64_msbe64_mfloat64_m1(const double *in, double *out, size_t a) {
    mfloat64m1_t m1 = mlbe64_m1(in, a);
    msbe64_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte8_msbte8_mint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlbte.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv128i8.i64(<vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte8_msbte8_mint8_m1(const int8_t *in1, int8_t *out, size_t a) {
    mint8m1_t m1 = mlbte8_m1(in1, a);
    msbte8_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte8_msbte8_muint8_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlbte.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[OUT:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv128i8.i64(<vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte8_msbte8_muint8_m1(const uint8_t *in, uint8_t *out, size_t a) {
    muint8m1_t m1 = mlbte8_m1(in, a);
    msbte8_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte16_msbte16_mint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlbte.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte16_msbte16_mint16_m1(const int16_t *in, int16_t *out, size_t a) {
    mint16m1_t m1 = mlbte16_m1(in, a);
    msbte16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte16_msbte16_muint16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mlbte.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv64i16.i64(<vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte16_msbte16_muint16_m1(const uint16_t *in, uint16_t *out, size_t a) {
    muint16m1_t m1 = mlbte16_m1(in, a);
    msbte16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte16_msbte16_mfloat16_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlbte.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast half* [[OUT:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv64f16.i64(<vscale x 64 x half> [[TMP1]], <vscale x 64 x half>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte16_msbte16_mfloat16_m1(const _Float16 *in, _Float16 *out, size_t a) {
    mfloat16m1_t m1 = mlbte16_m1(in, a);
    msbte16_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte32_msbte32_mint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlbte.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte32_msbte32_mint32_m1(const int32_t *in, int32_t *out, size_t a) {
    mint32m1_t m1 = mlbte32_m1(in, a);
    msbte32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte32_msbte32_muint32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlbte.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte32_msbte32_muint32_m1(const uint32_t *in, uint32_t *out, size_t a) {
    muint32m1_t m1 = mlbte32_m1(in, a);
    msbte32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte32_msbte32_mfloat32_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlbte.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv32f32.i64(<vscale x 32 x float> [[TMP1]], <vscale x 32 x float>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte32_msbte32_mfloat32_m1(const float *in, float *out, size_t a) {
    mfloat32m1_t m1 = mlbte32_m1(in, a);
    msbte32_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte64_msbte64_mint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlbte.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP1]], <vscale x 16 x i64>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte64_msbte64_mint64_m1(const int64_t *in, int64_t *out, size_t a) {
    mint64m1_t m1 = mlbte64_m1(in, a);
    msbte64_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte64_msbte64_muint64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i64* [[IN:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlbte.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i64* [[OUT:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP1]], <vscale x 16 x i64>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte64_msbte64_muint64_m1(const uint64_t *in, uint64_t *out, size_t a) {
    muint64m1_t m1 = mlbte64_m1(in, a);
    msbte64_m(m1, out, a);

    return;
}

// CHECK-IR-RV64-LABEL: @test_mlbte64_msbte64_mfloat64_m1(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast double* [[IN:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x double> @llvm.riscv.mlbte.m.nxv16f64.i64(<vscale x 16 x double>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 16 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msbte.m.nxv16f64.i64(<vscale x 16 x double> [[TMP1]], <vscale x 16 x double>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR3]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mlbte64_msbte64_mfloat64_m1(const double *in, double *out, size_t a) {
    mfloat64m1_t m1 = mlbte64_m1(in, a);
    msbte64_m(m1, out, a);

    return;
}
