// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix -target-feature +experimental-v -target-feature +f -target-feature +d -disable-O0-optnone -emit-llvm %s -o - | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mswma_int32(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i16* [[IN1:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mla.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i16* [[IN2:%.*]] to <vscale x 64 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 64 x i16> @llvm.riscv.mla.m.nxv64i16.i64(<vscale x 64 x i16>* [[TMP2]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = bitcast i32* [[DEST:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP4]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP6:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mswma.mm.nxv32i32.nxv64i16(<vscale x 32 x i32> [[TMP5]], <vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP7:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mswma.h.mm.nxv32i32.nxv64i16(<vscale x 32 x i32> [[TMP6]], <vscale x 64 x i16> [[TMP1]], <vscale x 64 x i16> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP8:%.*]] = bitcast i32* [[DEST]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP7]], <vscale x 32 x i32>* [[TMP8]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mswma_int32(const int32_t *dest, const int16_t *in1,
                      const int16_t *in2, size_t a) {
    mint16_t m1 = mla_m(in1, a);
    mint16_t m2 = mla_m(in2, a);
    mint32_t d_m = mlc_m(dest, a);
    d_m = mswma_mm(d_m, m1, m2);
    d_m = mswma_h_mm(d_m, m1, m2);
    msc_m(d_m, dest, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mswma_int64(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN1:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mla.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i32* [[IN2:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mla.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP2]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = bitcast i64* [[DEST:%.*]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64.i64(<vscale x 16 x i64>* [[TMP4]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mswma.mm.nxv16i64.nxv32i32(<vscale x 16 x i64> [[TMP5]], <vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i64> @llvm.riscv.mswma.w.mm.nxv16i64.nxv32i32(<vscale x 16 x i64> [[TMP6]], <vscale x 32 x i32> [[TMP1]], <vscale x 32 x i32> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP8:%.*]] = bitcast i64* [[DEST]] to <vscale x 16 x i64>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv16i64.i64(<vscale x 16 x i64> [[TMP7]], <vscale x 16 x i64>* [[TMP8]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mswma_int64(const int64_t *dest, const int32_t *in1,
                      const int32_t *in2, size_t a) {
    mint32_t m1 = mla_m(in1, a);
    mint32_t m2 = mla_m(in2, a);
    mint64_t d_m = mlc_m(dest, a);
    d_m = mswma_mm(d_m, m1, m2);
    d_m = mswma_w_mm(d_m, m1, m2);
    msc_m(d_m, dest, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_msqma_int32(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mla.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[IN2:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mla.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP2]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = bitcast i32* [[DEST:%.*]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32.i64(<vscale x 32 x i32>* [[TMP4]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP6:%.*]] = call <vscale x 32 x i32> @llvm.riscv.msqma.mm.nxv32i32.nxv128i8(<vscale x 32 x i32> [[TMP5]], <vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP7:%.*]] = call <vscale x 32 x i32> @llvm.riscv.msqma.b.mm.nxv32i32.nxv128i8(<vscale x 32 x i32> [[TMP6]], <vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP8:%.*]] = bitcast i32* [[DEST]] to <vscale x 32 x i32>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msc.m.nxv32i32.i64(<vscale x 32 x i32> [[TMP7]], <vscale x 32 x i32>* [[TMP8]], i64 [[A]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_msqma_int32(const int32_t *dest, const int8_t *in1,
                      const int8_t *in2, size_t a) {
    mint8_t m1 = mla_m(in1, a);
    mint8_t m2 = mla_m(in2, a);
    mint32_t d_m = mlc_m(dest, a);
    d_m = msqma_mm(d_m, m1, m2);
    d_m = msqma_b_mm(d_m, m1, m2);
    msc_m(d_m, dest, a);
    return;
}
