// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix -target-feature +experimental-v -target-feature +f -target-feature +d -disable-O0-optnone -emit-llvm %s -o - | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mwmau_uint16m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast i8* [[IN1:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlae.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR4:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast i8* [[IN2:%.*]] to <vscale x 128 x i8>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 128 x i8> @llvm.riscv.mlae.m.nxv128i8.i64(<vscale x 128 x i8>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = bitcast i16* [[DEST:%.*]] to <vscale x 128 x i16>*
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = call <vscale x 128 x i16> @llvm.riscv.mlae.m.nxv128i16.i64(<vscale x 128 x i16>* [[TMP4]], i64 [[A]], i64 1) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP6:%.*]] = call <vscale x 128 x i16> @llvm.riscv.mwmau.mm.nxv128i16.nxv128i8(<vscale x 128 x i16> [[TMP5]], <vscale x 128 x i8> [[TMP1]], <vscale x 128 x i8> [[TMP3]]) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP7:%.*]] = bitcast i16* [[OUT:%.*]] to <vscale x 128 x i16>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv128i16.i64(<vscale x 128 x i16> [[TMP6]], <vscale x 128 x i16>* [[TMP7]], i64 [[A]], i64 1) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mwmau_uint16m2(const uint16_t *dest, const uint8_t *in1,
                       const uint8_t *in2, uint16_t *out, size_t a) {
    muint8m1_t m1 = mlae8_m1(in1, a);
    muint8m1_t m2 = mlae8_m1(in2, a);
    muint16m2_t d_m = mlae16_m2(dest, a);
    d_m = mwmau_mm(d_m, m1, m2);
    msae16_m(d_m, out, a);
    return;
}

