; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 128 x i8> @llvm.riscv.mla.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msa.m.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mla.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msa.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mla.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msa.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mla.m.nxv16i64(
  <vscale x 16 x i64>*,
  i64)

declare void @llvm.riscv.msa.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mla.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msa.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mla.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msa.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mla.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msa.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 128 x i8> @llvm.riscv.mbcae.m.nxv128i8(
  <vscale x 128 x i8>
)

declare <vscale x 64 x i16> @llvm.riscv.mbcae.m.nxv64i16(
  <vscale x 64 x i16>
)

declare <vscale x 32 x i32> @llvm.riscv.mbcae.m.nxv32i32(
  <vscale x 32 x i32>
)

declare <vscale x 16 x i64> @llvm.riscv.mbcae.m.nxv16i64(
  <vscale x 16 x i64>
)

declare <vscale x 64 x half> @llvm.riscv.mbcae.m.nxv64f16(
  <vscale x 64 x half>
)

declare <vscale x 32 x float> @llvm.riscv.mbcae.m.nxv32f32(
  <vscale x 32 x float>
)

declare <vscale x 16 x double> @llvm.riscv.mbcae.m.nxv16f64(
  <vscale x 16 x double>
)

define void @intrinsic_mlae_msae_i(<vscale x 128 x i8>* %0, <vscale x 64 x i16>* %1, <vscale x 32 x i32>* %2, <vscale x 16 x i64>* %3, i64 %4) nounwind {
; CHECK-LABEL: intrinsic_mlae_msae_i:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlae8.m tr0, (a0), a4
; CHECK-NEXT:    mlae16.m tr1, (a1), a4
; CHECK-NEXT:    mlae32.m tr2, (a2), a4
; CHECK-NEXT:    mlae64.m tr3, (a3), a4
; CHECK-NEXT:    mbcaee8.m tr0, tr0
; CHECK-NEXT:    mbcaee16.m tr1, tr1
; CHECK-NEXT:    mbcaee32.m tr2, tr2
; CHECK-NEXT:    mbcaee64.m tr3, tr3
; CHECK-NEXT:    msae8.m tr0, (a0), a4
; CHECK-NEXT:    msae16.m tr1, (a1), a4
; CHECK-NEXT:    msae32.m tr2, (a2), a4
; CHECK-NEXT:    msae64.m tr3, (a3), a4
; CHECK-NEXT:    ret
entry:

  %5 = call <vscale x 128 x i8> @llvm.riscv.mla.m.nxv128i8(
    <vscale x 128 x i8>* %0,
    i64 %4)

  %6 = call <vscale x 64 x i16> @llvm.riscv.mla.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %4)

  %7 = call <vscale x 32 x i32> @llvm.riscv.mla.m.nxv32i32(
    <vscale x 32 x i32>* %2,
    i64 %4)

  %8 = call <vscale x 16 x i64> @llvm.riscv.mla.m.nxv16i64(
    <vscale x 16 x i64>* %3,
    i64 %4)

  %9 = call <vscale x 128 x i8> @llvm.riscv.mbcae.m.nxv128i8(
    <vscale x 128 x i8> %5)

  %10 = call <vscale x 64 x i16> @llvm.riscv.mbcae.m.nxv64i16(
    <vscale x 64 x i16> %6)

  %11 = call <vscale x 32 x i32> @llvm.riscv.mbcae.m.nxv32i32(
    <vscale x 32 x i32> %7)

  %12 = call <vscale x 16 x i64> @llvm.riscv.mbcae.m.nxv16i64(
    <vscale x 16 x i64> %8)

  call void @llvm.riscv.msa.m.nxv128i8(
    <vscale x 128 x i8> %9,
    <vscale x 128 x i8>* %0,
    i64 %4)

  call void @llvm.riscv.msa.m.nxv64i16(
    <vscale x 64 x i16> %10,
    <vscale x 64 x i16>* %1,
    i64 %4)

  call void @llvm.riscv.msa.m.nxv32i32(
    <vscale x 32 x i32> %11,
    <vscale x 32 x i32>* %2,
    i64 %4)

  call void @llvm.riscv.msa.m.nxv16i64(
    <vscale x 16 x i64> %12,
    <vscale x 16 x i64>* %3,
    i64 %4)

  ret void
}

define void @intrinsic_mlae_msae_f(<vscale x 64 x half>* %0, <vscale x 32 x float>* %1, <vscale x 16 x double>* %2) nounwind {
; CHECK-LABEL: intrinsic_mlae_msae_f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a3, zero, 1
; CHECK-NEXT:    mlae16.m tr0, (a0), a3
; CHECK-NEXT:    mlae32.m tr1, (a1), a3
; CHECK-NEXT:    mlae64.m tr2, (a2), a3
; CHECK-NEXT:    mbcaee16.m tr0, tr0
; CHECK-NEXT:    mbcaee32.m tr1, tr1
; CHECK-NEXT:    mbcaee64.m tr2, tr2
; CHECK-NEXT:    msae16.m tr0, (a0), a3
; CHECK-NEXT:    msae32.m tr1, (a1), a3
; CHECK-NEXT:    msae64.m tr2, (a2), a3
; CHECK-NEXT:    ret

entry:

  %3 = call <vscale x 64 x half> @llvm.riscv.mla.m.nxv64f16(
    <vscale x 64 x half>* %0,
    i64 1)

  %4 = call <vscale x 32 x float> @llvm.riscv.mla.m.nxv32f32(
    <vscale x 32 x float>* %1,
    i64 1)

  %5 = call <vscale x 16 x double> @llvm.riscv.mla.m.nxv16f64(
    <vscale x 16 x double>* %2,
    i64 1)

  %6 = call <vscale x 64 x half> @llvm.riscv.mbcae.m.nxv64f16(
    <vscale x 64 x half> %3)

  %7 = call <vscale x 32 x float> @llvm.riscv.mbcae.m.nxv32f32(
    <vscale x 32 x float> %4)

  %8 = call <vscale x 16 x double> @llvm.riscv.mbcae.m.nxv16f64(
    <vscale x 16 x double> %5)

  call void @llvm.riscv.msa.m.nxv64f16(
    <vscale x 64 x half> %6,
    <vscale x 64 x half>* %0,
    i64 1)

  call void @llvm.riscv.msa.m.nxv32f32(
    <vscale x 32 x float> %7,
    <vscale x 32 x float>* %1,
    i64 1)

  call void @llvm.riscv.msa.m.nxv16f64(
    <vscale x 16 x double> %8,
    <vscale x 16 x double>* %2,
    i64 1)

  ret void
}
