; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msc.m.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
  <vscale x 16 x i64>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 128 x i8> @llvm.riscv.mncvtu.x.xw.m.nxv128i8(
  <vscale x 64 x i16>)

declare <vscale x 64 x i16> @llvm.riscv.mncvtu.x.xw.m.nxv64i16(
  <vscale x 32 x i32>)

declare <vscale x 32 x i32> @llvm.riscv.mncvtu.x.xw.m.nxv32i32(
  <vscale x 16 x i64>)

declare <vscale x 128 x i8> @llvm.riscv.mncvtu.b.h.m.nxv128i8(
  <vscale x 64 x i16>)

declare <vscale x 64 x i16> @llvm.riscv.mncvtu.h.w.m.nxv64i16(
  <vscale x 32 x i32>)

declare <vscale x 32 x i32> @llvm.riscv.mncvtu.w.dw.m.nxv32i32(
  <vscale x 16 x i64>)

declare <vscale x 128 x i8> @llvm.riscv.mncvtu.x.xq.m.nxv128i8(
  <vscale x 32 x i32>)

declare <vscale x 128 x i8> @llvm.riscv.mncvtu.b.w.m.nxv128i8(
  <vscale x 32 x i32>)

declare <vscale x 128 x i8> @llvm.riscv.mncvt.x.xw.m.nxv128i8(
  <vscale x 64 x i16>)

declare <vscale x 64 x i16> @llvm.riscv.mncvt.x.xw.m.nxv64i16(
  <vscale x 32 x i32>)

declare <vscale x 32 x i32> @llvm.riscv.mncvt.x.xw.m.nxv32i32(
  <vscale x 16 x i64>)

declare <vscale x 128 x i8> @llvm.riscv.mncvt.b.h.m.nxv128i8(
  <vscale x 64 x i16>)

declare <vscale x 64 x i16> @llvm.riscv.mncvt.h.w.m.nxv64i16(
  <vscale x 32 x i32>)

declare <vscale x 32 x i32> @llvm.riscv.mncvt.w.dw.m.nxv32i32(
  <vscale x 16 x i64>)

declare <vscale x 128 x i8> @llvm.riscv.mncvt.x.xq.m.nxv128i8(
  <vscale x 32 x i32>)

declare <vscale x 128 x i8> @llvm.riscv.mncvt.b.w.m.nxv128i8(
  <vscale x 32 x i32>)

define void @intrinsic_mncvtu_x_xw(<vscale x 128 x i8>* %0, <vscale x 64 x i16>* %1, <vscale x 32 x i32>* %2, <vscale x 16 x i64>* %3, i64 %4) nounwind {
; CHECK-LABEL: intrinsic_mncvtu_x_xw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a1), a4
; CHECK-NEXT:    mncvtu.x.xw.m acc1, acc0
; CHECK-NEXT:    msce8.m acc1, (a0), a4
; CHECK-NEXT:    mncvtu.b.h.m acc0, acc0
; CHECK-NEXT:    msce8.m acc0, (a0), a4
; CHECK-NEXT:    mlce32.m acc0, (a2), a4
; CHECK-NEXT:    mncvtu.x.xw.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a1), a4
; CHECK-NEXT:    mncvtu.h.w.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a1), a4
; CHECK-NEXT:    mlce64.m acc1, (a3), a4
; CHECK-NEXT:    mncvtu.x.xw.m acc2, acc1
; CHECK-NEXT:    msce32.m acc2, (a2), a4
; CHECK-NEXT:    mncvtu.w.dw.m acc1, acc1
; CHECK-NEXT:    msce32.m acc1, (a2), a4
; CHECK-NEXT:    mncvtu.x.xq.m acc1, acc0
; CHECK-NEXT:    mncvtu.b.w.m acc0, acc0
; CHECK-NEXT:    msce8.m acc1, (a0), a4
; CHECK-NEXT:    msce8.m acc0, (a0), a4
; CHECK-NEXT:    ret
entry:
  %5 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %6 = call <vscale x 128 x i8> @llvm.riscv.mncvtu.x.xw.m.nxv128i8(
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %6,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  %7 = call <vscale x 128 x i8> @llvm.riscv.mncvtu.b.h.m.nxv128i8(
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %7,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  %8 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %9 = call <vscale x 64 x i16> @llvm.riscv.mncvtu.x.xw.m.nxv64i16(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %9,
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %10 = call <vscale x 64 x i16> @llvm.riscv.mncvtu.h.w.m.nxv64i16(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %10,
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %11 = call <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
    <vscale x 16 x i64>* %3,
    i64 %4
  )

  %12 = call <vscale x 32 x i32> @llvm.riscv.mncvtu.x.xw.m.nxv32i32(
    <vscale x 16 x i64> %11
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %12,
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %13 = call <vscale x 32 x i32> @llvm.riscv.mncvtu.w.dw.m.nxv32i32(
    <vscale x 16 x i64> %11
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %13,
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %14 = call <vscale x 128 x i8> @llvm.riscv.mncvtu.x.xq.m.nxv128i8(
    <vscale x 32 x i32> %8
  )

  %15 = call <vscale x 128 x i8> @llvm.riscv.mncvtu.b.w.m.nxv128i8(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %14,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %15,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  ret void
}

define void @intrinsic_mncvt_x_xw(<vscale x 128 x i8>* %0, <vscale x 64 x i16>* %1, <vscale x 32 x i32>* %2, <vscale x 16 x i64>* %3, i64 %4) nounwind {
; CHECK-LABEL: intrinsic_mncvt_x_xw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a1), a4
; CHECK-NEXT:    mncvt.x.xw.m acc1, acc0
; CHECK-NEXT:    msce8.m acc1, (a0), a4
; CHECK-NEXT:    mncvt.b.h.m acc0, acc0
; CHECK-NEXT:    msce8.m acc0, (a0), a4
; CHECK-NEXT:    mlce32.m acc0, (a2), a4
; CHECK-NEXT:    mncvt.x.xw.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a1), a4
; CHECK-NEXT:    mncvt.h.w.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a1), a4
; CHECK-NEXT:    mlce64.m acc1, (a3), a4
; CHECK-NEXT:    mncvt.x.xw.m acc2, acc1
; CHECK-NEXT:    msce32.m acc2, (a2), a4
; CHECK-NEXT:    mncvt.w.dw.m acc1, acc1
; CHECK-NEXT:    msce32.m acc1, (a2), a4
; CHECK-NEXT:    mncvt.x.xq.m acc1, acc0
; CHECK-NEXT:    mncvt.b.w.m acc0, acc0
; CHECK-NEXT:    msce8.m acc1, (a0), a4
; CHECK-NEXT:    msce8.m acc0, (a0), a4
; CHECK-NEXT:    ret
entry:
  %5 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %6 = call <vscale x 128 x i8> @llvm.riscv.mncvt.x.xw.m.nxv128i8(
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %6,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  %7 = call <vscale x 128 x i8> @llvm.riscv.mncvt.b.h.m.nxv128i8(
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %7,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  %8 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %9 = call <vscale x 64 x i16> @llvm.riscv.mncvt.x.xw.m.nxv64i16(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %9,
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %10 = call <vscale x 64 x i16> @llvm.riscv.mncvt.h.w.m.nxv64i16(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %10,
    <vscale x 64 x i16>* %1,
    i64 %4
  )

  %11 = call <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
    <vscale x 16 x i64>* %3,
    i64 %4
  )

  %12 = call <vscale x 32 x i32> @llvm.riscv.mncvt.x.xw.m.nxv32i32(
    <vscale x 16 x i64> %11
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %12,
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %13 = call <vscale x 32 x i32> @llvm.riscv.mncvt.w.dw.m.nxv32i32(
    <vscale x 16 x i64> %11
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %13,
    <vscale x 32 x i32>* %2,
    i64 %4
  )

  %14 = call <vscale x 128 x i8> @llvm.riscv.mncvt.x.xq.m.nxv128i8(
    <vscale x 32 x i32> %8
  )

  %15 = call <vscale x 128 x i8> @llvm.riscv.mncvt.b.w.m.nxv128i8(
    <vscale x 32 x i32> %8
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %14,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  call void @llvm.riscv.msc.m.nxv128i8(
    <vscale x 128 x i8> %15,
    <vscale x 128 x i8>* %0,
    i64 %4
  )

  ret void
}
