; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msc.m.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
  <vscale x 16 x i64>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mfcvtu.x.f.m.nxv64i16(
  <vscale x 64 x half>)

declare <vscale x 32 x i32> @llvm.riscv.mfcvtu.x.f.m.nxv32i32(
  <vscale x 32 x float>)

declare <vscale x 16 x i64> @llvm.riscv.mfcvtu.x.f.m.nxv16i64(
  <vscale x 16 x double>)

declare <vscale x 64 x i16> @llvm.riscv.mfcvtu.h.hf.m.nxv64i16(
  <vscale x 64 x half>)

declare <vscale x 32 x i32> @llvm.riscv.mfcvtu.w.f.m.nxv32i32(
  <vscale x 32 x float>)

declare <vscale x 16 x i64> @llvm.riscv.mfcvtu.dw.d.m.nxv16i64(
  <vscale x 16 x double>)

define void @intrinsic_mfcvtu(<vscale x 64 x i16>* %0, <vscale x 64 x half>* %1, <vscale x 32 x i32>* %2, <vscale x 32 x float>* %3, <vscale x 16 x i64>* %4, <vscale x 16 x double>* %5, i64 %6) nounwind {
; CHECK-LABEL: intrinsic_mfcvtu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a1), a6
; CHECK-NEXT:    mfcvtu.x.f.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a0), a6
; CHECK-NEXT:    mfcvtu.h.hf.m acc0, acc0
; CHECK-NEXT:    msce16.m acc0, (a0), a6
; CHECK-NEXT:    mlce32.m acc0, (a3), a6
; CHECK-NEXT:    mfcvtu.x.f.m acc1, acc0
; CHECK-NEXT:    msce32.m acc1, (a2), a6
; CHECK-NEXT:    mfcvtu.w.f.m acc0, acc0
; CHECK-NEXT:    msce32.m acc0, (a2), a6
; CHECK-NEXT:    mlce64.m acc0, (a5), a6
; CHECK-NEXT:    mfcvtu.x.f.m acc1, acc0
; CHECK-NEXT:    msce64.m acc1, (a4), a6
; CHECK-NEXT:    mfcvtu.dw.d.m acc0, acc0
; CHECK-NEXT:    msce64.m acc0, (a4), a6
; CHECK-NEXT:    ret
entry:
  %7 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %6
  )

  %8 = call <vscale x 64 x i16> @llvm.riscv.mfcvtu.x.f.m.nxv64i16(
    <vscale x 64 x half> %7
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %8,
    <vscale x 64 x i16>* %0,
    i64 %6)

  %9 = call <vscale x 64 x i16> @llvm.riscv.mfcvtu.h.hf.m.nxv64i16(
    <vscale x 64 x half> %7
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %9,
    <vscale x 64 x i16>* %0,
    i64 %6)

  %10 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %3,
    i64 %6
  )

  %11 = call <vscale x 32 x i32> @llvm.riscv.mfcvtu.x.f.m.nxv32i32(
    <vscale x 32 x float> %10
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %11,
    <vscale x 32 x i32>* %2,
    i64 %6)

  %12 = call <vscale x 32 x i32> @llvm.riscv.mfcvtu.w.f.m.nxv32i32(
    <vscale x 32 x float> %10
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %12,
    <vscale x 32 x i32>* %2,
    i64 %6)

  %13 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %5,
    i64 %6
  )

  %14 = call <vscale x 16 x i64> @llvm.riscv.mfcvtu.x.f.m.nxv16i64(
    <vscale x 16 x double> %13
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %14,
    <vscale x 16 x i64>* %4,
    i64 %6)

  %15 = call <vscale x 16 x i64> @llvm.riscv.mfcvtu.dw.d.m.nxv16i64(
    <vscale x 16 x double> %13
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %15,
    <vscale x 16 x i64>* %4,
    i64 %6)

  ret void
}
