; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msc.m.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
  <vscale x 16 x i64>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mfwcvtu.fw.x.m.nxv64f16(
  <vscale x 128 x i8>)

declare <vscale x 64 x half> @llvm.riscv.mfwcvtu.hf.b.m.nxv64f16(
  <vscale x 128 x i8>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvtu.fw.x.m.nxv32f32(
  <vscale x 64 x i16>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvtu.f.h.m.nxv32f32(
  <vscale x 64 x i16>)

declare <vscale x 16 x double> @llvm.riscv.mfwcvtu.fw.x.m.nxv16f64(
  <vscale x 32 x i32>)

declare <vscale x 16 x double> @llvm.riscv.mfwcvtu.d.w.m.nxv16f64(
  <vscale x 32 x i32>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvtu.fq.x.m.nxv32f32(
  <vscale x 128 x i8>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvtu.f.b.m.nxv32f32(
  <vscale x 128 x i8>)

define void @intrinsic_mfwcvtu(<vscale x 128 x i8>* %0, <vscale x 64 x i16>* %1, <vscale x 64 x half>* %2, <vscale x 32 x i32>* %3, <vscale x 32 x float>* %4, <vscale x 16 x double>* %5, i64 %6) nounwind {
; CHECK-LABEL: intrinsic_mfwcvtu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce8.m acc0, (a0), a6
; CHECK-NEXT:    mfwcvtu.fw.x.m acc1, acc0
; CHECK-NEXT:    mfwcvtu.hf.b.m acc2, acc0
; CHECK-NEXT:    msce16.m acc1, (a2), a6
; CHECK-NEXT:    msce16.m acc2, (a2), a6
; CHECK-NEXT:    mlce16.m acc1, (a1), a6
; CHECK-NEXT:    mfwcvtu.fw.x.m acc2, acc1
; CHECK-NEXT:    mfwcvtu.f.h.m acc1, acc1
; CHECK-NEXT:    msce32.m acc2, (a4), a6
; CHECK-NEXT:    msce32.m acc1, (a4), a6
; CHECK-NEXT:    mlce32.m acc1, (a3), a6
; CHECK-NEXT:    mfwcvtu.fw.x.m acc2, acc1
; CHECK-NEXT:    mfwcvtu.d.w.m acc1, acc1
; CHECK-NEXT:    msce64.m acc2, (a5), a6
; CHECK-NEXT:    msce64.m acc1, (a5), a6
; CHECK-NEXT:    mfwcvtu.fq.x.m acc1, acc0
; CHECK-NEXT:    mfwcvtu.f.b.m acc0, acc0
; CHECK-NEXT:    msce32.m acc1, (a4), a6
; CHECK-NEXT:    msce32.m acc0, (a4), a6
; CHECK-NEXT:    ret
entry:
  %7 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %0,
    i64 %6
  )

  %8 = call <vscale x 64 x half> @llvm.riscv.mfwcvtu.fw.x.m.nxv64f16(
    <vscale x 128 x i8> %7
  )

  %9 = call <vscale x 64 x half> @llvm.riscv.mfwcvtu.hf.b.m.nxv64f16(
    <vscale x 128 x i8> %7
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %8,
    <vscale x 64 x half>* %2,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %9,
    <vscale x 64 x half>* %2,
    i64 %6
  )

  %10 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %6
  )

  %11 = call <vscale x 32 x float> @llvm.riscv.mfwcvtu.fw.x.m.nxv32f32(
    <vscale x 64 x i16> %10
  )

  %12 = call <vscale x 32 x float> @llvm.riscv.mfwcvtu.f.h.m.nxv32f32(
    <vscale x 64 x i16> %10
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %11,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %12,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  %13 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %3,
    i64 %6
  )

  %14 = call <vscale x 16 x double> @llvm.riscv.mfwcvtu.fw.x.m.nxv16f64(
    <vscale x 32 x i32> %13
  )

  %15 = call <vscale x 16 x double> @llvm.riscv.mfwcvtu.d.w.m.nxv16f64(
    <vscale x 32 x i32> %13
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %14,
    <vscale x 16 x double>* %5,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %15,
    <vscale x 16 x double>* %5,
    i64 %6
  )

  %16 = call <vscale x 32 x float> @llvm.riscv.mfwcvtu.fq.x.m.nxv32f32(
    <vscale x 128 x i8> %7
  )

  %17 = call <vscale x 32 x float> @llvm.riscv.mfwcvtu.f.b.m.nxv32f32(
    <vscale x 128 x i8> %7
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %16,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %17,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  ret void
}

declare <vscale x 64 x half> @llvm.riscv.mfwcvt.fw.x.m.nxv64f16(
  <vscale x 128 x i8>)

declare <vscale x 64 x half> @llvm.riscv.mfwcvt.hf.b.m.nxv64f16(
  <vscale x 128 x i8>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvt.fw.x.m.nxv32f32(
  <vscale x 64 x i16>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvt.f.h.m.nxv32f32(
  <vscale x 64 x i16>)

declare <vscale x 16 x double> @llvm.riscv.mfwcvt.fw.x.m.nxv16f64(
  <vscale x 32 x i32>)

declare <vscale x 16 x double> @llvm.riscv.mfwcvt.d.w.m.nxv16f64(
  <vscale x 32 x i32>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvt.fq.x.m.nxv32f32(
  <vscale x 128 x i8>)

declare <vscale x 32 x float> @llvm.riscv.mfwcvt.f.b.m.nxv32f32(
  <vscale x 128 x i8>)

define void @intrinsic_mfwcvt(<vscale x 128 x i8>* %0, <vscale x 64 x i16>* %1, <vscale x 64 x half>* %2, <vscale x 32 x i32>* %3, <vscale x 32 x float>* %4, <vscale x 16 x double>* %5, i64 %6) nounwind {
; CHECK-LABEL: intrinsic_mfwcvt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce8.m acc0, (a0), a6
; CHECK-NEXT:    mfwcvt.fw.x.m acc1, acc0
; CHECK-NEXT:    mfwcvt.hf.b.m acc2, acc0
; CHECK-NEXT:    msce16.m acc1, (a2), a6
; CHECK-NEXT:    msce16.m acc2, (a2), a6
; CHECK-NEXT:    mlce16.m acc1, (a1), a6
; CHECK-NEXT:    mfwcvt.fw.x.m acc2, acc1
; CHECK-NEXT:    mfwcvt.f.h.m acc1, acc1
; CHECK-NEXT:    msce32.m acc2, (a4), a6
; CHECK-NEXT:    msce32.m acc1, (a4), a6
; CHECK-NEXT:    mlce32.m acc1, (a3), a6
; CHECK-NEXT:    mfwcvt.fw.x.m acc2, acc1
; CHECK-NEXT:    mfwcvt.d.w.m acc1, acc1
; CHECK-NEXT:    msce64.m acc2, (a5), a6
; CHECK-NEXT:    msce64.m acc1, (a5), a6
; CHECK-NEXT:    mfwcvt.fq.x.m acc1, acc0
; CHECK-NEXT:    mfwcvt.f.b.m acc0, acc0
; CHECK-NEXT:    msce32.m acc1, (a4), a6
; CHECK-NEXT:    msce32.m acc0, (a4), a6
; CHECK-NEXT:    ret
entry:
  %7 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %0,
    i64 %6
  )

  %8 = call <vscale x 64 x half> @llvm.riscv.mfwcvt.fw.x.m.nxv64f16(
    <vscale x 128 x i8> %7
  )

  %9 = call <vscale x 64 x half> @llvm.riscv.mfwcvt.hf.b.m.nxv64f16(
    <vscale x 128 x i8> %7
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %8,
    <vscale x 64 x half>* %2,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %9,
    <vscale x 64 x half>* %2,
    i64 %6
  )

  %10 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %6
  )

  %11 = call <vscale x 32 x float> @llvm.riscv.mfwcvt.fw.x.m.nxv32f32(
    <vscale x 64 x i16> %10
  )

  %12 = call <vscale x 32 x float> @llvm.riscv.mfwcvt.f.h.m.nxv32f32(
    <vscale x 64 x i16> %10
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %11,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %12,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  %13 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %3,
    i64 %6
  )

  %14 = call <vscale x 16 x double> @llvm.riscv.mfwcvt.fw.x.m.nxv16f64(
    <vscale x 32 x i32> %13
  )

  %15 = call <vscale x 16 x double> @llvm.riscv.mfwcvt.d.w.m.nxv16f64(
    <vscale x 32 x i32> %13
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %14,
    <vscale x 16 x double>* %5,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %15,
    <vscale x 16 x double>* %5,
    i64 %6
  )

  %16 = call <vscale x 32 x float> @llvm.riscv.mfwcvt.fq.x.m.nxv32f32(
    <vscale x 128 x i8> %7
  )

  %17 = call <vscale x 32 x float> @llvm.riscv.mfwcvt.f.b.m.nxv32f32(
    <vscale x 128 x i8> %7
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %16,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %17,
    <vscale x 32 x float>* %4,
    i64 %6
  )

  ret void
}

declare <vscale x 64 x i16> @llvm.riscv.mfcvt.x.f.m.nxv64i16(
  <vscale x 64 x half>)

declare <vscale x 32 x i32> @llvm.riscv.mfcvt.x.f.m.nxv32i32(
  <vscale x 32 x float>)

declare <vscale x 16 x i64> @llvm.riscv.mfcvt.x.f.m.nxv16i64(
  <vscale x 16 x double>)

declare <vscale x 64 x i16> @llvm.riscv.mfcvt.h.hf.m.nxv64i16(
  <vscale x 64 x half>)

declare <vscale x 32 x i32> @llvm.riscv.mfcvt.w.f.m.nxv32i32(
  <vscale x 32 x float>)

declare <vscale x 16 x i64> @llvm.riscv.mfcvt.dw.d.m.nxv16i64(
  <vscale x 16 x double>)

define void @intrinsic_mfcvt(<vscale x 64 x i16>* %0, <vscale x 64 x half>* %1, <vscale x 32 x i32>* %2, <vscale x 32 x float>* %3, <vscale x 16 x i64>* %4, <vscale x 16 x double>* %5, i64 %6) nounwind {
; CHECK-LABEL: intrinsic_mfcvt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a1), a6
; CHECK-NEXT:    mfcvt.x.f.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a0), a6
; CHECK-NEXT:    mfcvt.h.hf.m acc0, acc0
; CHECK-NEXT:    msce16.m acc0, (a0), a6
; CHECK-NEXT:    mlce32.m acc0, (a3), a6
; CHECK-NEXT:    mfcvt.x.f.m acc1, acc0
; CHECK-NEXT:    msce32.m acc1, (a2), a6
; CHECK-NEXT:    mfcvt.w.f.m acc0, acc0
; CHECK-NEXT:    msce32.m acc0, (a2), a6
; CHECK-NEXT:    mlce64.m acc0, (a5), a6
; CHECK-NEXT:    mfcvt.x.f.m acc1, acc0
; CHECK-NEXT:    msce64.m acc1, (a4), a6
; CHECK-NEXT:    mfcvt.dw.d.m acc0, acc0
; CHECK-NEXT:    msce64.m acc0, (a4), a6
; CHECK-NEXT:    ret
entry:
  %7 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %6
  )

  %8 = call <vscale x 64 x i16> @llvm.riscv.mfcvt.x.f.m.nxv64i16(
    <vscale x 64 x half> %7
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %8,
    <vscale x 64 x i16>* %0,
    i64 %6)

  %9 = call <vscale x 64 x i16> @llvm.riscv.mfcvt.h.hf.m.nxv64i16(
    <vscale x 64 x half> %7
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %9,
    <vscale x 64 x i16>* %0,
    i64 %6)

  %10 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %3,
    i64 %6
  )

  %11 = call <vscale x 32 x i32> @llvm.riscv.mfcvt.x.f.m.nxv32i32(
    <vscale x 32 x float> %10
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %11,
    <vscale x 32 x i32>* %2,
    i64 %6)

  %12 = call <vscale x 32 x i32> @llvm.riscv.mfcvt.w.f.m.nxv32i32(
    <vscale x 32 x float> %10
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %12,
    <vscale x 32 x i32>* %2,
    i64 %6)

  %13 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %5,
    i64 %6
  )

  %14 = call <vscale x 16 x i64> @llvm.riscv.mfcvt.x.f.m.nxv16i64(
    <vscale x 16 x double> %13
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %14,
    <vscale x 16 x i64>* %4,
    i64 %6)

  %15 = call <vscale x 16 x i64> @llvm.riscv.mfcvt.dw.d.m.nxv16i64(
    <vscale x 16 x double> %13
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %15,
    <vscale x 16 x i64>* %4,
    i64 %6)

  ret void
}
