; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msc.m.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
  <vscale x 16 x i64>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mfncvtu.f.xw.m.nxv64f16(
  <vscale x 32 x i32>)

declare <vscale x 64 x half> @llvm.riscv.mfncvtu.hf.w.m.nxv64f16(
  <vscale x 32 x i32>)

declare <vscale x 32 x float> @llvm.riscv.mfncvtu.f.xw.m.nxv32f32(
  <vscale x 16 x i64>)

declare <vscale x 32 x float> @llvm.riscv.mfncvtu.f.dw.m.nxv32f32(
  <vscale x 16 x i64>)

define void @intrinsic_mfncvtu(<vscale x 64 x half>* %0, <vscale x 32 x i32>* %1, <vscale x 32 x float>* %2, <vscale x 16 x i64>* %3, i64 %4) nounwind {
; CHECK-LABEL: intrinsic_mfncvtu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a1), a4
; CHECK-NEXT:    mfncvtu.f.xw.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a0), a4
; CHECK-NEXT:    mfncvtu.hf.w.m acc0, acc0
; CHECK-NEXT:    msce16.m acc0, (a0), a4
; CHECK-NEXT:    mlce64.m acc0, (a3), a4
; CHECK-NEXT:    mfncvtu.f.xw.m acc1, acc0
; CHECK-NEXT:    msce32.m acc1, (a2), a4
; CHECK-NEXT:    mfncvtu.f.dw.m acc0, acc0
; CHECK-NEXT:    msce32.m acc0, (a2), a4
; CHECK-NEXT:    ret
entry:
  %5 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %1,
    i64 %4
  )

  %6 = call <vscale x 64 x half> @llvm.riscv.mfncvtu.f.xw.m.nxv64f16(
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %6,
    <vscale x 64 x half>* %0,
    i64 %4
  )

  %7 = call <vscale x 64 x half> @llvm.riscv.mfncvtu.hf.w.m.nxv64f16(
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %7,
    <vscale x 64 x half>* %0,
    i64 %4
  )

  %8 = call <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
    <vscale x 16 x i64>* %3,
    i64 %4
  )

  %9 = call <vscale x 32 x float> @llvm.riscv.mfncvtu.f.xw.m.nxv32f32(
    <vscale x 16 x i64> %8
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %9,
    <vscale x 32 x float>* %2,
    i64 %4
  )

  %10 = call <vscale x 32 x float> @llvm.riscv.mfncvtu.f.dw.m.nxv32f32(
    <vscale x 16 x i64> %8
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %10,
    <vscale x 32 x float>* %2,
    i64 %4
  )

  ret void
}

declare <vscale x 64 x half> @llvm.riscv.mfncvt.f.xw.m.nxv64f16(
  <vscale x 32 x i32>)

declare <vscale x 64 x half> @llvm.riscv.mfncvt.hf.w.m.nxv64f16(
  <vscale x 32 x i32>)

declare <vscale x 32 x float> @llvm.riscv.mfncvt.f.xw.m.nxv32f32(
  <vscale x 16 x i64>)

declare <vscale x 32 x float> @llvm.riscv.mfncvt.f.dw.m.nxv32f32(
  <vscale x 16 x i64>)

define void @intrinsic_mfncvt(<vscale x 64 x half>* %0, <vscale x 32 x i32>* %1, <vscale x 32 x float>* %2, <vscale x 16 x i64>* %3, i64 %4) nounwind {
; CHECK-LABEL: intrinsic_mfncvt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a1), a4
; CHECK-NEXT:    mfncvt.f.xw.m acc1, acc0
; CHECK-NEXT:    msce16.m acc1, (a0), a4
; CHECK-NEXT:    mfncvt.hf.w.m acc0, acc0
; CHECK-NEXT:    msce16.m acc0, (a0), a4
; CHECK-NEXT:    mlce64.m acc0, (a3), a4
; CHECK-NEXT:    mfncvt.f.xw.m acc1, acc0
; CHECK-NEXT:    msce32.m acc1, (a2), a4
; CHECK-NEXT:    mfncvt.f.dw.m acc0, acc0
; CHECK-NEXT:    msce32.m acc0, (a2), a4
; CHECK-NEXT:    ret
entry:
  %5 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %1,
    i64 %4
  )

  %6 = call <vscale x 64 x half> @llvm.riscv.mfncvt.f.xw.m.nxv64f16(
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %6,
    <vscale x 64 x half>* %0,
    i64 %4
  )

  %7 = call <vscale x 64 x half> @llvm.riscv.mfncvt.hf.w.m.nxv64f16(
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %7,
    <vscale x 64 x half>* %0,
    i64 %4
  )

  %8 = call <vscale x 16 x i64> @llvm.riscv.mlc.m.nxv16i64(
    <vscale x 16 x i64>* %3,
    i64 %4
  )

  %9 = call <vscale x 32 x float> @llvm.riscv.mfncvt.f.xw.m.nxv32f32(
    <vscale x 16 x i64> %8
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %9,
    <vscale x 32 x float>* %2,
    i64 %4
  )

  %10 = call <vscale x 32 x float> @llvm.riscv.mfncvt.f.dw.m.nxv32f32(
    <vscale x 16 x i64> %8
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %10,
    <vscale x 32 x float>* %2,
    i64 %4
  )

  ret void
}
