; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mfmax.mm.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>
)

define void @intrinsic_mfmax_mm_nxv64f16(<vscale x 64 x half>* %0, <vscale x 64 x half>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_mm_nxv64f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a2
; CHECK-NEXT:    mlce16.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.mm acc0, acc0, acc1
; CHECK-NEXT:    msce16.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %0,
    i64 %2
  )

  %4 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %2
  )

  %5 = call <vscale x 64 x half> @llvm.riscv.mfmax.mm.nxv64f16(
    <vscale x 64 x half> %3,
    <vscale x 64 x half> %4
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %5,
    <vscale x 64 x half>* %0,
    i64 %2
  )

  ret void
}

declare <vscale x 64 x half> @llvm.riscv.mfmax.hf.mm.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>
)

define void @intrinsic_mfmax_hf_mm_nxv64f16(<vscale x 64 x half>* %0, <vscale x 64 x half>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_hf_mm_nxv64f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a2
; CHECK-NEXT:    mlce16.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.hf.mm acc0, acc0, acc1
; CHECK-NEXT:    msce16.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %0,
    i64 %2
  )

  %4 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %2
  )

  %5 = call <vscale x 64 x half> @llvm.riscv.mfmax.hf.mm.nxv64f16(
    <vscale x 64 x half> %3,
    <vscale x 64 x half> %4
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %5,
    <vscale x 64 x half>* %0,
    i64 %2
  )

  ret void
}

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mfmax.mm.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>
)

define void @intrinsic_mfmax_mm_nxv32f32(<vscale x 32 x float>* %0, <vscale x 32 x float>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_mm_nxv32f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a2
; CHECK-NEXT:    mlce32.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.mm acc0, acc0, acc1
; CHECK-NEXT:    msce32.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %0,
    i64 %2
  )

  %4 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %1,
    i64 %2
  )

  %5 = call <vscale x 32 x float> @llvm.riscv.mfmax.mm.nxv32f32(
    <vscale x 32 x float> %3,
    <vscale x 32 x float> %4
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %5,
    <vscale x 32 x float>* %0,
    i64 %2
  )

  ret void
}

declare <vscale x 32 x float> @llvm.riscv.mfmax.f.mm.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>
)

define void @intrinsic_mfmax_f_mm_nxv32f32(<vscale x 32 x float>* %0, <vscale x 32 x float>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_f_mm_nxv32f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a2
; CHECK-NEXT:    mlce32.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.f.mm acc0, acc0, acc1
; CHECK-NEXT:    msce32.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %0,
    i64 %2
  )

  %4 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %1,
    i64 %2
  )

  %5 = call <vscale x 32 x float> @llvm.riscv.mfmax.f.mm.nxv32f32(
    <vscale x 32 x float> %3,
    <vscale x 32 x float> %4
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %5,
    <vscale x 32 x float>* %0,
    i64 %2
  )

  ret void
}

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mfmax.mm.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>
)

define void @intrinsic_mfmax_mm_nxv16f64(<vscale x 16 x double>* %0, <vscale x 16 x double>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_mm_nxv16f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce64.m acc0, (a0), a2
; CHECK-NEXT:    mlce64.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.mm acc0, acc0, acc1
; CHECK-NEXT:    msce64.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %0,
    i64 %2
  )

  %4 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %1,
    i64 %2
  )

  %5 = call <vscale x 16 x double> @llvm.riscv.mfmax.mm.nxv16f64(
    <vscale x 16 x double> %3,
    <vscale x 16 x double> %4
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %5,
    <vscale x 16 x double>* %0,
    i64 %2
  )

  ret void
}

declare <vscale x 16 x double> @llvm.riscv.mfmax.d.mm.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>
)

define void @intrinsic_mfmax_d_mm_nxv16f64(<vscale x 16 x double>* %0, <vscale x 16 x double>* %1, i64 %2) {
; CHECK-LABEL: intrinsic_mfmax_d_mm_nxv16f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce64.m acc0, (a0), a2
; CHECK-NEXT:    mlce64.m acc1, (a1), a2
; CHECK-NEXT:    mfmax.d.mm acc0, acc0, acc1
; CHECK-NEXT:    msce64.m acc0, (a0), a2
; CHECK-NEXT:    ret
entry:
  %3 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %0,
    i64 %2
  )

  %4 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %1,
    i64 %2
  )

  %5 = call <vscale x 16 x double> @llvm.riscv.mfmax.d.mm.nxv16f64(
    <vscale x 16 x double> %3,
    <vscale x 16 x double> %4
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %5,
    <vscale x 16 x double>* %0,
    i64 %2
  )

  ret void
}
