; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x half> @llvm.riscv.mla.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mlb.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mfma.mm.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>,
  <vscale x 64 x half>
)

define void @intrinsic_mfma_mm_nxv64f16(<vscale x 64 x half>* %0, <vscale x 64 x half>* %1, <vscale x 64 x half>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_mm_nxv64f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a3
; CHECK-NEXT:    mlae16.m tr0, (a1), a3
; CHECK-NEXT:    mlbe16.m tr1, (a2), a3
; CHECK-NEXT:    mfma.mm acc0, tr0, tr1
; CHECK-NEXT:    msce16.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %0,
    i64 %3
  )

  %5 = call <vscale x 64 x half> @llvm.riscv.mla.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %3
  )

  %6 = call <vscale x 64 x half> @llvm.riscv.mlb.m.nxv64f16(
    <vscale x 64 x half>* %2,
    i64 %3
  )

  %7 = call <vscale x 64 x half> @llvm.riscv.mfma.mm.nxv64f16(
    <vscale x 64 x half> %4,
    <vscale x 64 x half> %5,
    <vscale x 64 x half> %6
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %7,
    <vscale x 64 x half>* %0,
    i64 %3
  )

  ret void
}

declare <vscale x 64 x half> @llvm.riscv.mfma.hf.mm.nxv64f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>,
  <vscale x 64 x half>
)

define void @intrinsic_mfma_hf_mm_nxv64f16(<vscale x 64 x half>* %0, <vscale x 64 x half>* %1, <vscale x 64 x half>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_hf_mm_nxv64f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a3
; CHECK-NEXT:    mlae16.m tr0, (a1), a3
; CHECK-NEXT:    mlbe16.m tr1, (a2), a3
; CHECK-NEXT:    mfma.hf.mm acc0, tr0, tr1
; CHECK-NEXT:    msce16.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv64f16(
    <vscale x 64 x half>* %0,
    i64 %3
  )

  %5 = call <vscale x 64 x half> @llvm.riscv.mla.m.nxv64f16(
    <vscale x 64 x half>* %1,
    i64 %3
  )

  %6 = call <vscale x 64 x half> @llvm.riscv.mlb.m.nxv64f16(
    <vscale x 64 x half>* %2,
    i64 %3
  )

  %7 = call <vscale x 64 x half> @llvm.riscv.mfma.hf.mm.nxv64f16(
    <vscale x 64 x half> %4,
    <vscale x 64 x half> %5,
    <vscale x 64 x half> %6
  )

  call void @llvm.riscv.msc.m.nxv64f16(
    <vscale x 64 x half> %7,
    <vscale x 64 x half>* %0,
    i64 %3
  )

  ret void
}

declare <vscale x 32 x float> @llvm.riscv.mla.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mlb.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mfma.mm.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>,
  <vscale x 32 x float>
)

define void @intrinsic_mfma_mm_nxv32f32(<vscale x 32 x float>* %0, <vscale x 32 x float>* %1, <vscale x 32 x float>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_mm_nxv32f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a3
; CHECK-NEXT:    mlae32.m tr0, (a1), a3
; CHECK-NEXT:    mlbe32.m tr1, (a2), a3
; CHECK-NEXT:    mfma.mm acc0, tr0, tr1
; CHECK-NEXT:    msce32.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %0,
    i64 %3
  )

  %5 = call <vscale x 32 x float> @llvm.riscv.mla.m.nxv32f32(
    <vscale x 32 x float>* %1,
    i64 %3
  )

  %6 = call <vscale x 32 x float> @llvm.riscv.mlb.m.nxv32f32(
    <vscale x 32 x float>* %2,
    i64 %3
  )

  %7 = call <vscale x 32 x float> @llvm.riscv.mfma.mm.nxv32f32(
    <vscale x 32 x float> %4,
    <vscale x 32 x float> %5,
    <vscale x 32 x float> %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %7,
    <vscale x 32 x float>* %0,
    i64 %3
  )

  ret void
}

declare <vscale x 32 x float> @llvm.riscv.mfma.f.mm.nxv32f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>,
  <vscale x 32 x float>
)

define void @intrinsic_mfma_f_mm_nxv32f32(<vscale x 32 x float>* %0, <vscale x 32 x float>* %1, <vscale x 32 x float>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_f_mm_nxv32f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a3
; CHECK-NEXT:    mlae32.m tr0, (a1), a3
; CHECK-NEXT:    mlbe32.m tr1, (a2), a3
; CHECK-NEXT:    mfma.f.mm acc0, tr0, tr1
; CHECK-NEXT:    msce32.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv32f32(
    <vscale x 32 x float>* %0,
    i64 %3
  )

  %5 = call <vscale x 32 x float> @llvm.riscv.mla.m.nxv32f32(
    <vscale x 32 x float>* %1,
    i64 %3
  )

  %6 = call <vscale x 32 x float> @llvm.riscv.mlb.m.nxv32f32(
    <vscale x 32 x float>* %2,
    i64 %3
  )

  %7 = call <vscale x 32 x float> @llvm.riscv.mfma.f.mm.nxv32f32(
    <vscale x 32 x float> %4,
    <vscale x 32 x float> %5,
    <vscale x 32 x float> %6
  )

  call void @llvm.riscv.msc.m.nxv32f32(
    <vscale x 32 x float> %7,
    <vscale x 32 x float>* %0,
    i64 %3
  )

  ret void
}

declare <vscale x 16 x double> @llvm.riscv.mla.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mlb.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mfma.mm.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>,
  <vscale x 16 x double>
)

define void @intrinsic_mfma_mm_nxv16f64(<vscale x 16 x double>* %0, <vscale x 16 x double>* %1, <vscale x 16 x double>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_mm_nxv16f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce64.m acc0, (a0), a3
; CHECK-NEXT:    mlae64.m tr0, (a1), a3
; CHECK-NEXT:    mlbe64.m tr1, (a2), a3
; CHECK-NEXT:    mfma.mm acc0, tr0, tr1
; CHECK-NEXT:    msce64.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %0,
    i64 %3
  )

  %5 = call <vscale x 16 x double> @llvm.riscv.mla.m.nxv16f64(
    <vscale x 16 x double>* %1,
    i64 %3
  )

  %6 = call <vscale x 16 x double> @llvm.riscv.mlb.m.nxv16f64(
    <vscale x 16 x double>* %2,
    i64 %3
  )

  %7 = call <vscale x 16 x double> @llvm.riscv.mfma.mm.nxv16f64(
    <vscale x 16 x double> %4,
    <vscale x 16 x double> %5,
    <vscale x 16 x double> %6
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %7,
    <vscale x 16 x double>* %0,
    i64 %3
  )

  ret void
}

declare <vscale x 16 x double> @llvm.riscv.mfma.d.mm.nxv16f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>,
  <vscale x 16 x double>
)

define void @intrinsic_mfma_d_mm_nxv16f64(<vscale x 16 x double>* %0, <vscale x 16 x double>* %1, <vscale x 16 x double>* %2, i64 %3) nounwind {
; CHECK-LABEL: intrinsic_mfma_d_mm_nxv16f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce64.m acc0, (a0), a3
; CHECK-NEXT:    mlae64.m tr0, (a1), a3
; CHECK-NEXT:    mlbe64.m tr1, (a2), a3
; CHECK-NEXT:    mfma.d.mm acc0, tr0, tr1
; CHECK-NEXT:    msce64.m acc0, (a0), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv16f64(
    <vscale x 16 x double>* %0,
    i64 %3
  )

  %5 = call <vscale x 16 x double> @llvm.riscv.mla.m.nxv16f64(
    <vscale x 16 x double>* %1,
    i64 %3
  )

  %6 = call <vscale x 16 x double> @llvm.riscv.mlb.m.nxv16f64(
    <vscale x 16 x double>* %2,
    i64 %3
  )

  %7 = call <vscale x 16 x double> @llvm.riscv.mfma.d.mm.nxv16f64(
    <vscale x 16 x double> %4,
    <vscale x 16 x double> %5,
    <vscale x 16 x double> %6
  )

  call void @llvm.riscv.msc.m.nxv16f64(
    <vscale x 16 x double> %7,
    <vscale x 16 x double>* %0,
    i64 %3
  )

  ret void
}
