; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh -target-abi lp64d \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 32 x float> @llvm.riscv.mlc.m.nxv2f32(
  <vscale x 32 x float>*,
  i64)

declare void @llvm.riscv.msc.m.nxv2f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64)

declare <vscale x 32 x float> @llvm.riscv.mfmv.a.f.nxv2f32(
  <vscale x 32 x float>,
  float,
  i64)

define void @intrinsic_mfmv_nxv2f32(<vscale x 32 x float>* %0, <vscale x 32 x float>* %1, i64 %2) nounwind {
; CHECK-LABEL: intrinsic_mfmv_nxv2f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a2
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    flw ft0, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    mfmve32.a.f acc0, ft0, a2
; CHECK-NEXT:    msce32.m acc0, (a1), a2
; CHECK-NEXT:    ret
entry:

  %3 = call <vscale x 32 x float> @llvm.riscv.mlc.m.nxv2f32(<vscale x 32 x float>* %0, i64 %2)
  %4 = call <vscale x 32 x float> @llvm.riscv.mfmv.a.f.nxv2f32(<vscale x 32 x float> %3, float 6.0, i64 %2)
  call void @llvm.riscv.msc.m.nxv2f32( <vscale x 32 x float> %4, <vscale x 32 x float>* %1, i64 %2)

  ret void
}


declare <vscale x 64 x half> @llvm.riscv.mlc.m.nxv4f16(
  <vscale x 64 x half>*,
  i64)

declare void @llvm.riscv.msc.m.nxv4f16(
  <vscale x 64 x half>,
  <vscale x 64 x half>*,
  i64)

declare <vscale x 64 x half> @llvm.riscv.mfmv.a.f.nxv4f16(
  <vscale x 64 x half>,
  half,
  i64)

define void @intrinsic_mfmv_nxv4f16(<vscale x 64 x half>* %0, <vscale x 64 x half>* %1, i64 %2) nounwind {
; CHECK-LABEL: intrinsic_mfmv_nxv4f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a2
; CHECK-NEXT:    lui a0, %hi(.LCPI1_0)
; CHECK-NEXT:    flh ft0, %lo(.LCPI1_0)(a0)
; CHECK-NEXT:    mfmve16.a.f acc0, ft0, a2
; CHECK-NEXT:    msce16.m acc0, (a1), a2
; CHECK-NEXT:    ret
entry:

  %3 = call <vscale x 64 x half> @llvm.riscv.mlc.m.nxv4f16(<vscale x 64 x half>* %0, i64 %2)
  %4 = call <vscale x 64 x half> @llvm.riscv.mfmv.a.f.nxv4f16(<vscale x 64 x half> %3, half 6.0, i64 %2)
  call void @llvm.riscv.msc.m.nxv4f16( <vscale x 64 x half> %4, <vscale x 64 x half>* %1, i64 %2)

  ret void
}

declare <vscale x 16 x double> @llvm.riscv.mlc.m.nxv1f64(
  <vscale x 16 x double>*,
  i64)

declare void @llvm.riscv.msc.m.nxv1f64(
  <vscale x 16 x double>,
  <vscale x 16 x double>*,
  i64)

declare <vscale x 16 x double> @llvm.riscv.mfmv.a.f.nxv1f64(
  <vscale x 16 x double>,
  double,
  i64)

define void @intrinsic_mfmv_nxv1f64(<vscale x 16 x double>* %0, <vscale x 16 x double>* %1, i64 %2) nounwind {
; CHECK-LABEL: intrinsic_mfmv_nxv1f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce64.m acc0, (a0), a2
; CHECK-NEXT:    lui a0, %hi(.LCPI2_0)
; CHECK-NEXT:    fld ft0, %lo(.LCPI2_0)(a0)
; CHECK-NEXT:    mfmve64.a.f acc0, ft0, a2
; CHECK-NEXT:    msce64.m acc0, (a1), a2
; CHECK-NEXT:    ret
entry:

  %3 = call <vscale x 16 x double> @llvm.riscv.mlc.m.nxv1f64(<vscale x 16 x double>* %0, i64 %2)
  %4 = call <vscale x 16 x double> @llvm.riscv.mfmv.a.f.nxv1f64(<vscale x 16 x double> %3, double 6.0, i64 %2)
  call void @llvm.riscv.msc.m.nxv1f64( <vscale x 16 x double> %4, <vscale x 16 x double>* %1, i64 %2)

  ret void
}
