; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s
declare <vscale x 32 x float> @llvm.riscv.mlbe.m.nxv2f32(
  <vscale x 32 x float>*,
  i64, i64)

declare void @llvm.riscv.msbe.m.nxv2f32(
  <vscale x 32 x float>,
  <vscale x 32 x float>*,
  i64, i64)

define void @intrinsic_mlbe_msbe_nxv2f32(<vscale x 32 x float>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mlbe_msbe_nxv2f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlbe32.m tr0, (a0), a1, m1
; CHECK-NEXT:    msbe32.m tr0, (a0), a1, m1
; CHECK-NEXT:    ret
entry:

  %2 = call <vscale x 32 x float> @llvm.riscv.mlbe.m.nxv2f32(
    <vscale x 32 x float>* %0,
    i64 %1, i64 0)

  call void @llvm.riscv.msbe.m.nxv2f32(
    <vscale x 32 x float> %2,
    <vscale x 32 x float>* %0,
    i64 %1, i64 0)

  ret void
}

declare <vscale x 128 x i8> @llvm.riscv.mlbe.m.nxv8i8(
  <vscale x 128 x i8>*,
  i64, i64)

declare void @llvm.riscv.msbe.m.nxv8i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64, i64)

define void @intrinsic_mlbe_msbe_nxv8i8(<vscale x 128 x i8>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mlbe_msbe_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlbe8.m tr0, (a0), a1, m1
; CHECK-NEXT:    msbe8.m tr0, (a0), a1, m1
; CHECK-NEXT:    ret
entry:

  %2 = call <vscale x 128 x i8> @llvm.riscv.mlbe.m.nxv8i8(
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  call void @llvm.riscv.msbe.m.nxv8i8(
    <vscale x 128 x i8> %2,
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  ret void
}

declare <vscale x 128 x i8> @llvm.riscv.mlbte.m(
  <vscale x 128 x i8>*,
  i64, i64)

declare void @llvm.riscv.msbte.m(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64, i64)

define void @intrinsic_mlbte8_msbte8(<vscale x 128 x i8>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mlbte8_msbte8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlbte8.m tr0, (a0), a1, m1
; CHECK-NEXT:    msbte8.m tr0, (a0), a1, m1
; CHECK-NEXT:    ret
entry:

  %2 = call <vscale x 128 x i8> @llvm.riscv.mlbte.m(
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  call void @llvm.riscv.msbte.m(
    <vscale x 128 x i8> %2,
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  ret void
}
