; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 128 x i8> @llvm.riscv.mlre.m(
  <vscale x 128 x i8>*,
  i64, i64)

declare void @llvm.riscv.msre.m(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>*,
  i64, i64)

define void @intrinsic_mlre8_msre8(<vscale x 128 x i8>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mlre8_msre8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlre8.m tr0, (a0), a1, m1
; CHECK-NEXT:    msre8.m tr0, (a0), a1, m1
; CHECK-NEXT:    ret
entry:

  %2 = call <vscale x 128 x i8> @llvm.riscv.mlre.m(
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  call void @llvm.riscv.msre.m(
    <vscale x 128 x i8> %2,
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  ret void
}
