; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh -target-abi lp64d \
; RUN:   -verify-machineinstrs < %s | FileCheck %s
declare <vscale x 128 x i8> @llvm.riscv.mlae.m.nxv8i8(
  <vscale x 128 x i8>*,
  i64, i64)

declare <vscale x 64 x i16> @llvm.riscv.mlae.m.nxv4i16(
  <vscale x 64 x i16>*,
  i64, i64)

declare <vscale x 32 x i32> @llvm.riscv.mlae.m.nxv2i32(
  <vscale x 32 x i32>*,
  i64, i64)

declare <vscale x 16 x i64> @llvm.riscv.mlae.m.nxv1i64(
  <vscale x 16 x i64>*,
  i64, i64)

declare i8 @llvm.riscv.mmv.x.s.nxv8i8(
  <vscale x 128 x i8>,
  i64
)

define signext i8 @intrinsic_mmv_nxv8i8(<vscale x 128 x i8>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mmv_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlae8.m tr0, (a0), a1, m1
; CHECK-NEXT:    mmv.x.s a0, tr0, a1
; CHECK-NEXT:    ret
entry:
  %2 = call <vscale x 128 x i8> @llvm.riscv.mlae.m.nxv8i8(
    <vscale x 128 x i8>* %0,
    i64 %1, i64 0)

  %3 = call i8 @llvm.riscv.mmv.x.s.nxv8i8(<vscale x 128 x i8> %2, i64 %1)

  ret i8 %3
}


declare i16 @llvm.riscv.mmv.x.s.nxv4i16(
  <vscale x 64 x i16>,
  i64
)


define signext i16 @intrinsic_mmv_nxv4i16(<vscale x 64 x i16>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mmv_nxv4i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlae16.m tr0, (a0), a1, m1
; CHECK-NEXT:    mmv.x.s a0, tr0, a1
; CHECK-NEXT:    ret
entry:
  %2 = call <vscale x 64 x i16> @llvm.riscv.mlae.m.nxv4i16(
    <vscale x 64 x i16>* %0,
    i64 %1, i64 0)

  %3 = call i16 @llvm.riscv.mmv.x.s.nxv4i16(<vscale x 64 x i16> %2, i64 %1)

  ret i16 %3
}

declare i32 @llvm.riscv.mmv.x.s.nxv2i32(
  <vscale x 32 x i32>,
  i64
)

define signext i32 @intrinsic_mmv_x_s_nxv2i32(<vscale x 32 x i32>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mmv_x_s_nxv2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlae32.m tr0, (a0), a1, m1
; CHECK-NEXT:    mmv.x.s a0, tr0, a1
; CHECK-NEXT:    ret
entry:
  %2 = call <vscale x 32 x i32> @llvm.riscv.mlae.m.nxv2i32(
    <vscale x 32 x i32>* %0,
    i64 %1, i64 0)

  %3 = call i32 @llvm.riscv.mmv.x.s.nxv2i32(<vscale x 32 x i32> %2, i64 %1)

  ret i32 %3
}

declare i64 @llvm.riscv.mmv.x.s.nxv1i64(
  <vscale x 16 x i64>,
  i64
)

define i64 @intrinsic_mmv_x_s_nxv1i64(<vscale x 16 x i64>* %0, i64 %1) nounwind {
; CHECK-LABEL: intrinsic_mmv_x_s_nxv1i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlae64.m tr0, (a0), a1, m1
; CHECK-NEXT:    mmv.x.s a0, tr0, a1
; CHECK-NEXT:    ret
entry:
  %2 = call <vscale x 16 x i64> @llvm.riscv.mlae.m.nxv1i64(
    <vscale x 16 x i64>* %0,
    i64 %1, i64 0)

  %3 = call i64 @llvm.riscv.mmv.x.s.nxv1i64(<vscale x 16 x i64> %2, i64 %1)

  ret i64 %3
}

