; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
  <vscale x 128 x i8>*,
  i64)

declare void @llvm.riscv.msc.m.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>*,
  i64)

declare <vscale x 64 x i16> @llvm.riscv.mwsubu.mm.nxv64i16.nxv128i8.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>
)


define void @intrinsic_mwsubu_mm_nxv64i16_nxv128i8_nxv128i8(<vscale x 128 x i8>* %0, <vscale x 128 x i8>* %1, <vscale x 64 x i16>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_mm_nxv64i16_nxv128i8_nxv128i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce8.m acc0, (a0), a3
; CHECK-NEXT:    mlce8.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.mm acc0, acc0, acc1
; CHECK-NEXT:    msce16.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %0,
    i64 %3
  )

  %5 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %1,
    i64 %3
  )

  %6 = call <vscale x 64 x i16> @llvm.riscv.mwsubu.mm.nxv64i16.nxv128i8.nxv128i8(
    <vscale x 128 x i8> %4,
    <vscale x 128 x i8> %5
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %6,
    <vscale x 64 x i16>* %2,
    i64 %3
  )

  ret void
}

declare <vscale x 64 x i16> @llvm.riscv.mwsubu.b.mm.nxv64i16.nxv128i8.nxv128i8(
  <vscale x 128 x i8>,
  <vscale x 128 x i8>
)


define void @intrinsic_mwsubu_b_mm_nxv64i16_nxv128i8_nxv128i8(<vscale x 128 x i8>* %0, <vscale x 128 x i8>* %1, <vscale x 64 x i16>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_b_mm_nxv64i16_nxv128i8_nxv128i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce8.m acc0, (a0), a3
; CHECK-NEXT:    mlce8.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.b.mm acc0, acc0, acc1
; CHECK-NEXT:    msce16.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %0,
    i64 %3
  )

  %5 = call <vscale x 128 x i8> @llvm.riscv.mlc.m.nxv128i8(
    <vscale x 128 x i8>* %1,
    i64 %3
  )

  %6 = call <vscale x 64 x i16> @llvm.riscv.mwsubu.b.mm.nxv64i16.nxv128i8.nxv128i8(
    <vscale x 128 x i8> %4,
    <vscale x 128 x i8> %5
  )

  call void @llvm.riscv.msc.m.nxv64i16(
    <vscale x 64 x i16> %6,
    <vscale x 64 x i16>* %2,
    i64 %3
  )

  ret void
}

; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
  <vscale x 64 x i16>*,
  i64)

declare void @llvm.riscv.msc.m.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>*,
  i64)

declare <vscale x 32 x i32> @llvm.riscv.mwsubu.mm.nxv32i32.nxv64i16.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>
)


define void @intrinsic_mwsubu_mm_nxv32i32_nxv64i16_nxv64i16(<vscale x 64 x i16>* %0, <vscale x 64 x i16>* %1, <vscale x 32 x i32>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_mm_nxv32i32_nxv64i16_nxv64i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a3
; CHECK-NEXT:    mlce16.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.mm acc0, acc0, acc1
; CHECK-NEXT:    msce32.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %0,
    i64 %3
  )

  %5 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %3
  )

  %6 = call <vscale x 32 x i32> @llvm.riscv.mwsubu.mm.nxv32i32.nxv64i16.nxv64i16(
    <vscale x 64 x i16> %4,
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %6,
    <vscale x 32 x i32>* %2,
    i64 %3
  )

  ret void
}

declare <vscale x 32 x i32> @llvm.riscv.mwsubu.h.mm.nxv32i32.nxv64i16.nxv64i16(
  <vscale x 64 x i16>,
  <vscale x 64 x i16>
)


define void @intrinsic_mwsubu_h_mm_nxv32i32_nxv64i16_nxv64i16(<vscale x 64 x i16>* %0, <vscale x 64 x i16>* %1, <vscale x 32 x i32>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_h_mm_nxv32i32_nxv64i16_nxv64i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce16.m acc0, (a0), a3
; CHECK-NEXT:    mlce16.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.h.mm acc0, acc0, acc1
; CHECK-NEXT:    msce32.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %0,
    i64 %3
  )

  %5 = call <vscale x 64 x i16> @llvm.riscv.mlc.m.nxv64i16(
    <vscale x 64 x i16>* %1,
    i64 %3
  )

  %6 = call <vscale x 32 x i32> @llvm.riscv.mwsubu.h.mm.nxv32i32.nxv64i16.nxv64i16(
    <vscale x 64 x i16> %4,
    <vscale x 64 x i16> %5
  )

  call void @llvm.riscv.msc.m.nxv32i32(
    <vscale x 32 x i32> %6,
    <vscale x 32 x i32>* %2,
    i64 %3
  )

  ret void
}

; RUN: llc -mtriple=riscv64 -mattr=+experimental-matrix -mattr=+experimental-v,+d,+experimental-zfh \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
  <vscale x 32 x i32>*,
  i64)

declare void @llvm.riscv.msc.m.nxv16i64(
  <vscale x 16 x i64>,
  <vscale x 16 x i64>*,
  i64)

declare <vscale x 16 x i64> @llvm.riscv.mwsubu.mm.nxv16i64.nxv32i32.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>
)


define void @intrinsic_mwsubu_mm_nxv16i64_nxv32i32_nxv32i32(<vscale x 32 x i32>* %0, <vscale x 32 x i32>* %1, <vscale x 16 x i64>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_mm_nxv16i64_nxv32i32_nxv32i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a3
; CHECK-NEXT:    mlce32.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.mm acc0, acc0, acc1
; CHECK-NEXT:    msce64.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %0,
    i64 %3
  )

  %5 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %1,
    i64 %3
  )

  %6 = call <vscale x 16 x i64> @llvm.riscv.mwsubu.mm.nxv16i64.nxv32i32.nxv32i32(
    <vscale x 32 x i32> %4,
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %6,
    <vscale x 16 x i64>* %2,
    i64 %3
  )

  ret void
}

declare <vscale x 16 x i64> @llvm.riscv.mwsubu.w.mm.nxv16i64.nxv32i32.nxv32i32(
  <vscale x 32 x i32>,
  <vscale x 32 x i32>
)


define void @intrinsic_mwsubu_w_mm_nxv16i64_nxv32i32_nxv32i32(<vscale x 32 x i32>* %0, <vscale x 32 x i32>* %1, <vscale x 16 x i64>* %2, i64 %3) {
; CHECK-LABEL: intrinsic_mwsubu_w_mm_nxv16i64_nxv32i32_nxv32i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mlce32.m acc0, (a0), a3
; CHECK-NEXT:    mlce32.m acc1, (a1), a3
; CHECK-NEXT:    mwsubu.w.mm acc0, acc0, acc1
; CHECK-NEXT:    msce64.m acc0, (a2), a3
; CHECK-NEXT:    ret
entry:
  %4 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %0,
    i64 %3
  )

  %5 = call <vscale x 32 x i32> @llvm.riscv.mlc.m.nxv32i32(
    <vscale x 32 x i32>* %1,
    i64 %3
  )

  %6 = call <vscale x 16 x i64> @llvm.riscv.mwsubu.w.mm.nxv16i64.nxv32i32.nxv32i32(
    <vscale x 32 x i32> %4,
    <vscale x 32 x i32> %5
  )

  call void @llvm.riscv.msc.m.nxv16i64(
    <vscale x 16 x i64> %6,
    <vscale x 16 x i64>* %2,
    i64 %3
  )

  ret void
}
