// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-matrix \
// RUN: -target-feature +experimental-v -target-feature +f -target-feature +d \
// RUN: -target-feature +experimental-zfh -disable-O0-optnone -emit-llvm %s -o - \
// RUN: | opt -S -mem2reg | FileCheck --check-prefix=CHECK-IR-RV64 %s


#include <riscv_matrix.h>

// CHECK-IR-RV64-LABEL: @test_mfwmul_mm_float32m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast half* [[IN1:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlae.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR4:[0-9]+]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast half* [[IN2:%.*]] to <vscale x 64 x half>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 64 x half> @llvm.riscv.mlae.m.nxv64f16.i64(<vscale x 64 x half>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 64 x float> @llvm.riscv.mfwmul.mm.nxv64f32.nxv64f16.i64(<vscale x 64 x half> [[TMP1]], <vscale x 64 x half> [[TMP3]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 64 x float>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv64f32.i64(<vscale x 64 x float> [[TMP4]], <vscale x 64 x float>* [[TMP5]], i64 [[A]], i64 1) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwmul_mm_float32m2(const _Float16 *in1, const _Float16 *in2, float *out, size_t a) {
    mfloat16_t m1 = mla_m(in1, a);
    mfloat16_t m2 = mla_m(in2, a);
    mfloat32m2_t mo = mfwmul_mm(m1, m2);
    msa_m(mo, out, a);
    return;
}

// CHECK-IR-RV64-LABEL: @test_mfwmul_mm_float64m2(
// CHECK-IR-RV64-NEXT:  entry:
// CHECK-IR-RV64-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN1:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP1:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlae.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP0]], i64 [[A:%.*]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP2:%.*]] = bitcast float* [[IN2:%.*]] to <vscale x 32 x float>*
// CHECK-IR-RV64-NEXT:    [[TMP3:%.*]] = call <vscale x 32 x float> @llvm.riscv.mlae.m.nxv32f32.i64(<vscale x 32 x float>* [[TMP2]], i64 [[A]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP4:%.*]] = call <vscale x 32 x double> @llvm.riscv.mfwmul.mm.nxv32f64.nxv32f32.i64(<vscale x 32 x float> [[TMP1]], <vscale x 32 x float> [[TMP3]], i64 0) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    [[TMP5:%.*]] = bitcast double* [[OUT:%.*]] to <vscale x 32 x double>*
// CHECK-IR-RV64-NEXT:    call void @llvm.riscv.msae.m.nxv32f64.i64(<vscale x 32 x double> [[TMP4]], <vscale x 32 x double>* [[TMP5]], i64 [[A]], i64 1) #[[ATTR4]]
// CHECK-IR-RV64-NEXT:    ret void
//
void test_mfwmul_mm_float64m2(const float *in1, const float *in2, double *out, size_t a) {
    mfloat32_t m1 = mla_m(in1, a);
    mfloat32_t m2 = mla_m(in2, a);
    mfloat64m2_t mo = mfwmul_mm(m1, m2);
    msa_m(mo, out, a);
    return;
}
